/* The coroutine task table (docs/topics/CONCURRENCY.md 4.4, slice C).
 *
 * What a task is: the **place** a coroutine's storage hangs off. `spawn` enters that place
 * lazily and records it here; every step makes it current; the task's end releases the whole
 * place in one go.
 *
 * Why a table and not just the frame's mark: the author's decision for slice C is that the task
 * is **owned** rather than merely scoped. Keeping the record here is what makes
 *
 *   - running to completion and an explicit drop the *same* release (`extc_task_end`),
 *   - a scheduler able to enumerate what is still live (`extc_task_live`), and
 *   - the frame able to hold only its own id (`task`), with the zone read once at the spawn and
 *     stored beside it for the step to use -- a resume never re-derives the place from the
 *     environment (rule 1).
 *
 * The frame still carries the zone itself: a step reads it from there, which is what the J1
 * check in `tools/check_concurrency_guards.py` enforces (no `extc_zoneTop` inside a `$step`).
 */
#include "coroutine.h"

void coroutineEmitRuntime(Arena *a, Buf *out) {
    (void)a;
    bufPuts(out,
        "/* The two pool primitives this table sits on: declared here because the pool runtime is\n"
        " * emitted on demand, and a program that only spawns coroutines never pulls it in by itself\n"
        " * (`genCoroDecls` marks the pool runtime needed as well, which is what defines them). */\n"
        "int64_t extc_pool_zoneEnter(void);\n"
        "void    extc_pool_zoneLeaveTo(int64_t mark);\n"
        "int64_t extc_pool_zoneNewRoot(void);\n"
        "void    extc_pool_zoneFreeRoot(int64_t zi);\n"
        "/* ---- coroutine task table (docs/topics/CONCURRENCY.md 4.4) ----\n"
        " * A task is the place its coroutine's storage hangs off: entered at the spawn, made\n"
        " * current for every step, and released in one go when the task ends. The table is what\n"
        " * makes the task owned rather than scoped -- running to completion and an explicit drop\n"
        " * are the same release, and a scheduler can ask what is still live. */\n"
        "static int64_t *extc_taskZone;\n"
        "static uint8_t *extc_taskLive;\n"
        "static int64_t  extc_taskCap;\n"
        "static int64_t  extc_taskNext;\n"
        "/* The task's **own arena**: what a task allocates lives here and goes in one release, the\n"
        " * same shape as a block arena or a pool plate. A boxed coroutine's frame is the first\n"
        " * tenant -- it must outlive the C scope that spawned it. */\n"
        "static extc_arena *extc_taskArena;\n"
        "/* Begins a task: enters its own place, records it, and hands both back -- the zone for the\n"
        " * frame and the id for the table. */\n"
        "int64_t extc_task_begin(void) {\n"
        "    /* The task's place is a **root** slot: not on the block stack, so no enclosing block\n"
        "     * leave and no other task's end can pop it, and ending this task can release exactly\n"
        "     * its own storage whenever that happens (定案 99: a task's lifetime is not LIFO). */\n"
        "    int64_t zone = extc_pool_zoneNewRoot();\n"
        "    if (extc_taskNext == extc_taskCap) {\n"
        "        int64_t cap = extc_taskCap ? extc_taskCap * 2 : 16;\n"
        "        int64_t *z = (int64_t *)realloc(extc_taskZone, (size_t)cap * sizeof *z);\n"
        "        uint8_t *l = (uint8_t *)realloc(extc_taskLive, (size_t)cap * sizeof *l);\n"
        "        extc_arena *a = (extc_arena *)realloc(extc_taskArena, (size_t)cap * sizeof *a);\n"
        "        if (!z || !l || !a) { fputs(\"extc: out of memory\\n\", stderr); exit(70); }\n"
        "        extc_taskZone = z; extc_taskLive = l; extc_taskArena = a;\n"
        "        for (int64_t i = extc_taskCap; i < cap; i++) {\n"
        "            extc_taskLive[i] = 0;\n"
        "            extc_taskArena[i].top = NULL; extc_taskArena[i].spare = NULL;\n"
        "        }\n"
        "        extc_taskCap = cap;\n"
        "    }\n"
        "    extc_taskZone[extc_taskNext] = zone;\n"
        "    extc_taskLive[extc_taskNext] = 1;\n"
        "    extc_taskArena[extc_taskNext].top = NULL;\n"
        "    extc_taskArena[extc_taskNext].spare = NULL;\n"
        "    return extc_taskNext++;\n"
        "}\n"
        "/* A task's own place as an allocator: the frame of a boxed coroutine lives here, and so does\n"
        " * anything the coroutine allocates with `new` (slice C's promotion). */\n"
        "void *extc_task_alloc(int64_t id, int64_t n, const char *path, int line) {\n"
        "    if (id < 0 || id >= extc_taskCap || !extc_taskLive[id]) {\n"
        "        fputs(\"extc: allocation in a dead task\\n\", stderr); exit(70);\n"
        "    }\n"
        "    return extc_arena_alloc(&extc_taskArena[id], n, path, line);\n"
        "}\n"
        "/* The place a task's storage hangs off: the frame stores it, so a step reads the zone from\n"
        " * there instead of re-deriving it (rule 1). */\n"
        "int64_t extc_task_zone(int64_t id) {\n"
        "    if (id < 0 || id >= extc_taskCap) return -1;\n"
        "    return extc_taskZone[id];\n"
        "}\n"
        "/* Ends a task at any time: the same release whether it ran to completion or was dropped. */\n"
        "void extc_task_end(int64_t id) {\n"
        "    if (id < 0 || id >= extc_taskCap || !extc_taskLive[id]) return;\n"
        "    extc_taskLive[id] = 0;\n"
        "    /* The task's own arena, spare included: `extc_arena_release` keeps one block for reuse,\n"
        "     * and a task never runs again -- with one arena per task that block would outlive its\n"
        "     * purpose forever (measured: 200000 finished boxed tasks, RSS 29 MB, ~147 B each --\n"
        "     * exactly one frame block per task). 定案 99 says destroy. */\n"
        "    extc_arena_destroy(&extc_taskArena[id]);\n"
        "    /* Its own place in one go too -- precisely, whatever the stack looks like: the old\n"
        "     * `zoneLeaveTo` popped every zone above this one (killing live tasks) or nothing at\n"
        "     * all (leaking), because it assumed the task was the topmost place. */\n"
        "    extc_pool_zoneFreeRoot(extc_taskZone[id]);\n"
        "}\n"
        "/* Is this one task still alive? A handle outlives its task only by mistake: driving one\n"
        " * must trap loudly, not touch the freed place the frame lived in. */\n"
        "int64_t extc_task_alive(int64_t id) {\n"
        "    return (id >= 0 && id < extc_taskCap && extc_taskLive[id]) ? 1 : 0;\n"
        "}\n"
        "/* How many tasks are still live: what a scheduler (or a judge) asks. */\n"
        "int64_t extc_task_live(void) {\n"
        "    int64_t n = 0;\n"
        "    for (int64_t i = 0; i < extc_taskCap; i++) if (extc_taskLive[i]) n++;\n"
        "    return n;\n"
        "}\n");



}

/* ---- The event layer: epoll + AF_UNIX sockets (the scheduler's real event source) ----
 * Only scalars and one pointer cross the boundary: the `epoll_event` buffer lives in here, so a
 * platform struct never crosses into extC. Emitted on its own (not with the task table) because a
 * program may drive fds without ever spawning a coroutine. */
void eventEmitRuntime(Arena *arena, Buf *out) {
    (void)arena;
    bufPuts(out,
        "\n/* ---- The event layer: epoll + AF_UNIX sockets ----\n"
        " * Only scalars and one pointer cross the boundary: the `epoll_event` buffer lives in here. */\n"
        "#include <sys/epoll.h>\n"
        "#include <sys/socket.h>\n"
        "#include <sys/time.h>   /* `struct timeval`：收发超时 ✓ */\n"
        "#include <sys/un.h>\n"
        "#include <netinet/in.h>\n"
        "#include <netinet/tcp.h>\n"
        "#include <fcntl.h>\n"
        "#include <errno.h>\n\n"
        "int64_t extc_epoll_new(void) { return (int64_t)epoll_create1(0); }\n\n"
        "/* `tag` 跟着事件一起回来（epoll 的 user-data）—— 调度器把**任务行号**放进来，\n"
        " * 于是一个事件就是一次 O(1) 的定位，不必再扫任务表 ✗（这正是 10k 空闲连接\n"
        " * 就把吞吐砍半的那处）。listener 用 -1 这个哨兵。 */\n"
        "int64_t extc_epoll_add(int64_t ep, int64_t fd, int64_t readable, int64_t tag) {\n"
        "    struct epoll_event ev;\n"
        "    memset(&ev, 0, sizeof ev);\n"
        "    ev.events = readable ? EPOLLIN : EPOLLOUT;\n"
        "    ev.data.u64 = (uint64_t)tag;\n"
        "    return (int64_t)epoll_ctl((int)ep, EPOLL_CTL_ADD, (int)fd, &ev);\n"
        "}\n\n"
        "/* 一轮就绪事件写进**调用方给的缓冲**，返回个数（0 = 超时，<0 = 出错）。\n"
        " * 从前这里有 `static int64_t pending[64]` 的环形队列、每次吐一个 tag —— 那意味着\n"
        " * **一个进程只能有一个事件循环**，而且那段隐藏状态既不可重入也不可观察。\n"
        " * 现在缓冲由调用方拥有：多实例、可重入、容量自己定（level-triggered 语义下\n"
        " * 没取完的事件下一轮还会报，所以 `cap` 小也不会丢 ✓）。 */\n"
        "int64_t extc_epoll_wait_into(int64_t ep, int64_t *out, int64_t cap, int64_t timeout_ms) {\n"
        "    if (cap <= 0) return -1;\n"
        "    if (cap > 64) cap = 64;\n"
        "    struct epoll_event evs[64];\n"
        "    int n = epoll_wait((int)ep, evs, (int)cap, (int)timeout_ms);\n"
        "    if (n <= 0) return (int64_t)n;\n"
        "    for (int i = 0; i < n; i++) out[i] = (int64_t)evs[i].data.u64;\n"
        "    return (int64_t)n;\n"
        "}\n\n"
        "/* 登记兴趣：**第一次 ADD、之后 MOD**。TLS 会在同一个 fd 上来回切读/写等待\n"
        " * （`SSL_read` 要可读、`SSL_write` 要可写），只有 ADD 的话第二次会 EEXIST。 */\n"
        "int64_t extc_epoll_arm(int64_t ep, int64_t fd, int64_t readable, int64_t tag) {\n"
        "    struct epoll_event ev;\n"
        "    memset(&ev, 0, sizeof ev);\n"
        "    ev.events = readable ? EPOLLIN : EPOLLOUT;\n"
        "    ev.data.u64 = (uint64_t)tag;\n"
        "    if (epoll_ctl((int)ep, EPOLL_CTL_ADD, (int)fd, &ev) == 0) return 0;\n"
        "    return (int64_t)epoll_ctl((int)ep, EPOLL_CTL_MOD, (int)fd, &ev);\n"
        "}\n\n"        "/* 明文 socket 的读：**把「还没数据」与「连接已死」分开**。\n"
        " * 从前的 `recv` 返回值里这两种都是负数 ⇒ 会话层只能一律当成「等就绪」⇒\n"
        " * 对端 RST/退出后调用方**永远等下去**（实测：epoll 每轮立刻报可读、recv 每轮报错，\n"
        " * 客户端原地空转 500 轮 ✗）。-1000 = 现在没数据（等就绪再试）· -1001 = 连接坏了。 */\n"
        "int64_t extc_sock_read_why(int64_t fd, uint8_t *buf, int64_t n) {\n"
        "    ssize_t r = recv((int)fd, buf, (size_t)n, 0);\n"
        "    if (r >= 0) return (int64_t)r;\n"
        "    if (errno == EAGAIN || errno == EWOULDBLOCK) return -1000;\n"
        "    return -1001;\n"
        "}\n\n"
        "/* 写一侧同理：缓冲满 vs 连接坏了。 */\n"
        "int64_t extc_sock_write_why(int64_t fd, uint8_t *buf, int64_t n) {\n"
        "    ssize_t r = send((int)fd, buf, (size_t)n, MSG_NOSIGNAL);\n"
        "    if (r >= 0) return (int64_t)r;\n"
        "    if (errno == EAGAIN || errno == EWOULDBLOCK) return -1000;\n"
        "    return -1001;\n"
        "}\n\n"        "int64_t extc_sock_pair(int64_t *out) {\n"
        "    int sv[2];\n"
        "    if (socketpair(AF_UNIX, SOCK_STREAM, 0, sv) != 0) return -1;\n"
        "    out[0] = (int64_t)sv[0];\n"
        "    out[1] = (int64_t)sv[1];\n"
        "    return 0;\n"
        "}\n\n"
        "int64_t extc_sock_read(int64_t fd, uint8_t *buf, int64_t n) {\n"
        "    /* recv/send, not read/write: `std::sys::io` already claims those two names with a\n"
        "     * different signature, and both would land in the same translation unit. */\n"
        "    return (int64_t)recv((int)fd, buf, (size_t)n, 0);\n"
        "}\n\n"
        "int64_t extc_sock_write(int64_t fd, uint8_t *buf, int64_t n) {\n"
        "    return (int64_t)send((int)fd, buf, (size_t)n, 0);\n"
        "}\n\n"
        "int64_t extc_sock_nonblock(int64_t fd) {\n"
        "    int fl = fcntl((int)fd, F_GETFL, 0);\n"
        "    return fl < 0 ? -1 : fcntl((int)fd, F_SETFL, fl | O_NONBLOCK);\n"
        "}\n\n"
        "/* Nagle off. Without this, many small writes plus the peer's delayed ACK add up to the\n"
        " * classic ~40ms stall: measured on the pipeline workload (1024B echo) the extC server\n"
        " * went from 363 req/s to millions once this was set. The Go side always sets it. */\n"
        "int64_t extc_sock_nodelay(int64_t fd) {\n"
        "    int one = 1;\n"
        "    return (int64_t)setsockopt((int)fd, IPPROTO_TCP, TCP_NODELAY,\n"
        "                              (const void *)&one, (socklen_t)sizeof(one));\n"
        "}\n\n"
        "/* An AF_UNIX listener. A path whose first byte is NUL is the abstract namespace: no file on\n"
        " * disk, no cleanup, and it disappears with the process -- which is what a test wants. */\n"
        "int64_t extc_unix_listen(uint8_t *path, int64_t len, int64_t backlog) {\n"
        "    struct sockaddr_un sa;\n"
        "    int fd = socket(AF_UNIX, SOCK_STREAM, 0);\n"
        "    if (fd < 0 || len <= 0 || len > (int64_t)sizeof sa.sun_path) return -1;\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sun_family = AF_UNIX;\n"
        "    memcpy(sa.sun_path, path, (size_t)len);\n"
        "    if (bind(fd, (struct sockaddr *)&sa, (socklen_t)sizeof sa) != 0) return -1;\n"
        "    if (listen(fd, (int)backlog) != 0) return -1;\n"
        "    /* **listener 必须非阻塞**：批量 `accept` 要一直抽到 EAGAIN；阻塞的 listener 会在\n"
        "     * backlog 抽干的瞬间把整个事件循环卡死（实测：50k 忙连接全部 ESTAB、却零响应 ✗）。 */\n"
        "    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);\n"
        "    extc_sock_nonblock(fd);          /* the loop accepts when epoll says readable */\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "int64_t extc_unix_connect(uint8_t *path, int64_t len) {\n"
        "    struct sockaddr_un sa;\n"
        "    int fd = socket(AF_UNIX, SOCK_STREAM, 0);\n"
        "    if (fd < 0 || len <= 0 || len > (int64_t)sizeof sa.sun_path) return -1;\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sun_family = AF_UNIX;\n"
        "    memcpy(sa.sun_path, path, (size_t)len);\n"
        "    if (connect(fd, (struct sockaddr *)&sa, (socklen_t)sizeof sa) != 0) return -1;\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "/* Non-blocking accept: -1 with EAGAIN when the backlog is empty. */\n"
        "int64_t extc_sock_accept(int64_t listener) {\n"
        "    int fd = accept((int)listener, NULL, NULL);\n"
        "    if (fd >= 0) extc_sock_nonblock(fd);\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "/* Closing an fd is `std::sys::io`'s `close` (the same `int close(int)` ABI). */\n");
    /* A second block: one `bufPuts` string may not exceed the 4095 bytes C99 guarantees. */
    bufPuts(out,
        "/* TCP on the loopback. `sockaddr_in`, `htons` and the address stay in here -- extC gets\n"
        " * scalars, exactly like the AF_UNIX side. Port 0 lets the kernel choose; read it back with\n"
        " * `extc_sock_local_port`. */\n"
        "/* 客户端：连到**给定 IP**（域名先走 `extc_dns_lookup` ✓）。返回 fd，失败 -1。 */\n"
        "/* 不 include <unistd.h>：会跟程序自己的 read/write 原型打架（老账 ✓）⇒ 就地声明 close ✓ */\n"
        "extern int close(int);\n\n"
        "int64_t extc_tcp_connect_to(uint8_t *ip, int64_t iplen, int64_t port) {\n"
        "    char name[64];\n"
        "    if (iplen <= 0 || iplen >= (int64_t)sizeof name) return -1;\n"
        "    memcpy(name, ip, (size_t)iplen);\n"
        "    name[iplen] = 0;\n"
        "    struct sockaddr_in sa;\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sin_family = AF_INET;\n"
        "    sa.sin_port = htons((uint16_t)port);\n"
        "    if (inet_pton(AF_INET, name, &sa.sin_addr) != 1) return -1;\n"
        "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
        "    if (fd < 0) return -1;\n"
        "    if (connect(fd, (struct sockaddr *)&sa, sizeof sa) != 0) { close(fd); return -1; }\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "/* 收发超时（毫秒，0 = 取消）：客户端不能因为对端不说话就永远挂着 ✓ */\n"
        "int64_t extc_sock_timeout(int64_t fd, int64_t ms) {\n"
        "    struct timeval tv;\n"
        "    tv.tv_sec = ms / 1000;\n"
        "    tv.tv_usec = (ms % 1000) * 1000;\n"
        "    if (setsockopt((int)fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof tv) != 0) return -1;\n"
        "    return (int64_t)setsockopt((int)fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof tv);\n"
        "}\n\n"
        "int64_t extc_tcp_listen(int64_t port, int64_t backlog) {\n"
        "    struct sockaddr_in sa;\n"
        "    int one = 1;\n"
        "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
        "    if (fd < 0) return -1;\n"
        "    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sin_family = AF_INET;\n"
        "    sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n"
        "    sa.sin_port = htons((uint16_t)port);\n"
        "    if (bind(fd, (struct sockaddr *)&sa, sizeof sa) != 0) return -1;\n"
        "    if (listen(fd, (int)backlog) != 0) return -1;\n"
        "    /* **listener 必须非阻塞**：批量 `accept` 要一直抽到 EAGAIN；阻塞的 listener 会在\n"
        "     * backlog 抽干的瞬间把整个事件循环卡死（实测：50k 忙连接全部 ESTAB、却零响应 ✗）。 */\n"
        "    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);\n"
        "    extc_sock_nonblock(fd);\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "/* The same listener, but with SO_REUSEPORT set **before** bind: N independent processes\n"
        " * may then bind this port, and the kernel spreads connections between them by flow hash.\n"
        " * That is the whole multi-process story -- no shared memory, no locks, no language change:\n"
        " * the pool registry and the task table stay per-process for free, and a dying worker takes\n"
        " * only its own connections with it.\n"
        " *\n"
        " * Measured (2026-09-28, 8 P-cores, loopback, 256 connections, HTTP keep-alive, the same\n"
        " * 50-line extC responder): 8 single-threaded processes did 1,317,455 req/s at 15 MB RSS,\n"
        " * against nginx 1.28.3 with 8 workers tuned to the teeth at 1,064,775 req/s and 249 MB.\n"
        " *\n"
        " * `-std=c11` is strict ANSI, so glibc hides the name (it lives behind __USE_MISC) while\n"
        " * still declaring SO_REUSEADDR: fall back to the Linux value the name expands to. */\n"
        "int64_t extc_tcp_listen_shared(int64_t port, int64_t backlog) {\n"
        "    struct sockaddr_in sa;\n"
        "    int one = 1;\n"
        "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
        "    if (fd < 0) return -1;\n"
        "    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one);\n"
        "#ifdef SO_REUSEPORT\n"
        "    setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &one, sizeof one);\n"
        "#else\n"
        "    setsockopt(fd, SOL_SOCKET, 15 /* SO_REUSEPORT */, &one, (socklen_t)sizeof one);\n"
        "#endif\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sin_family = AF_INET;\n"
        "    sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n"
        "    sa.sin_port = htons((uint16_t)port);\n"
        "    if (bind(fd, (struct sockaddr *)&sa, sizeof sa) != 0) return -1;\n"
        "    if (listen(fd, (int)backlog) != 0) return -1;\n"
        "    /* **listener 必须非阻塞**：批量 `accept` 要一直抽到 EAGAIN；阻塞的 listener 会在\n"
        "     * backlog 抽干的瞬间把整个事件循环卡死（实测：50k 忙连接全部 ESTAB、却零响应 ✗）。 */\n"
        "    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);\n"
        "    extc_sock_nonblock(fd);\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "int64_t extc_tcp_connect(int64_t port) {\n"
        "    struct sockaddr_in sa;\n"
        "    int fd = socket(AF_INET, SOCK_STREAM, 0);\n"
        "    if (fd < 0) return -1;\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    sa.sin_family = AF_INET;\n"
        "    sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);\n"
        "    sa.sin_port = htons((uint16_t)port);\n"
        "    if (connect(fd, (struct sockaddr *)&sa, sizeof sa) != 0) return -1;\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "int64_t extc_sock_local_port(int64_t fd) {\n"
        "    struct sockaddr_in sa;\n"
        "    socklen_t len = sizeof sa;\n"
        "    memset(&sa, 0, sizeof sa);\n"
        "    if (getsockname((int)fd, (struct sockaddr *)&sa, &len) != 0) return -1;\n"
        "    return (int64_t)ntohs(sa.sin_port);\n"
        "}\n\n"
        "/* Write from an offset: a partial write has to be resumed where it stopped, and extC has no\n"
        " * pointer arithmetic. */\n"
        "int64_t extc_sock_write_from(int64_t fd, uint8_t *buf, int64_t from, int64_t n) {\n"
        "    return (int64_t)send((int)fd, buf + from, (size_t)n, 0);\n"
        "}\n\n"
        "/* Half-close: the peer sees EOF, and this side can still read the echo back. */\n"
        "int64_t extc_sock_shutdown_wr(int64_t fd) {\n"
        "    return (int64_t)shutdown((int)fd, SHUT_WR);\n"
        "}\n");
}

/* DNS 那一小块单独发射：它跟协程/epoll 没关系（同步 `getaddrinfo` ✓），而运行时是**按需发射**的
 * ⇒ 放进协程块里，一个"只想解析域名"的程序会链接失败（实测 `undefined reference` ✗）。 */
void dnsEmitRuntime(Arena *a, Buf *out) {
    (void)a;
    bufPuts(out,
        "#include <netdb.h>\n"
        "#include <arpa/inet.h>\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "/* 域名 → 第一个 IPv4 点分串（写进调用者的 `out` ✓）。`sockaddr_in`/`getaddrinfo` 全留在这边，\n"
        " * extC 只拿长度与字符串 ✓。返回长度，失败 -1。\n"
        " * 同步阻塞：库这一层不做异步解析（QQBot 这类 API 一个进程解析几次就够 ✓）。 */\n"
        "int64_t extc_dns_lookup(uint8_t *host, int64_t hostlen, uint8_t *out, int64_t outcap) {\n"
        "    char name[256];\n"
        "    if (hostlen <= 0 || hostlen >= (int64_t)sizeof name) return -1;\n"
        "    memcpy(name, host, (size_t)hostlen);\n"
        "    name[hostlen] = 0;\n"
        "    struct addrinfo hints;\n"
        "    memset(&hints, 0, sizeof hints);\n"
        "    hints.ai_family = AF_INET;\n"
        "    hints.ai_socktype = SOCK_STREAM;\n"
        "    struct addrinfo *res = NULL;\n"
        "    if (getaddrinfo(name, NULL, &hints, &res) != 0 || !res) return -1;\n"
        "    char ip[INET_ADDRSTRLEN];\n"
        "    struct sockaddr_in *sa = (struct sockaddr_in *)res->ai_addr;\n"
        "    if (!inet_ntop(AF_INET, &sa->sin_addr, ip, sizeof ip)) { freeaddrinfo(res); return -1; }\n"
        "    freeaddrinfo(res);\n"
        "    int64_t n = (int64_t)strlen(ip);\n"
        "    if (n >= outcap) return -1;\n"
        "    memcpy(out, ip, (size_t)n);\n"
        "    return n;\n"
        "}\n\n");
}

/* 文件层：最小 HTTP 服务器要的那几个 shim。**独立发射**（按需，跟着声明走），
 * 不搭协程表的车 —— 那辆车的最终发射还被 `needCoroHandle` 之类的条件门着，实测拉不动 ✗。 */
void fileLayerEmitRuntime(Arena *a, Buf *out) {
    (void)a;
    /* 一个 `bufPuts` 字符串不许超 4095 字节（C99 保证）⇒ 分块。 */
    bufPuts(out,
        "/* ---- 文件层（最小 HTTP 服务器要的那几个）：`struct stat`、`off_t`、路径的 NUL 终止\n"
        " * 全都留在 C 侧 —— extC 只拿标量。理由是一条实测教训：把 `struct rusage` 镜像成前 5 个字段\n"
        " * 让 `getrusage` 越界写栈 ⇒ SIGSEGV；`struct stat` 比那更大更平台相关，不该让作者去声明布局。 */\n"
        "#include <sys/stat.h>\n"
        "/* 不 include <unistd.h>：它会和程序自己声明的 `read`/`write` 撞原型（`extern!` 那条老摩擦）。\n"
        " * `close` 我们自己声明一行就够。 */\n"
        "extern int close(int);\n"
        "#include <sys/sendfile.h>\n"
        "#include <fcntl.h>\n"
                "#include <time.h>\n"
        "int64_t extc_file_open(uint8_t *path, int64_t len, int64_t *out_size, int64_t *out_mtime,\n"
        "                       int64_t *out_isdir) {\n"
        "    char p[4096];   /* 不用 PATH_MAX：`-std=c11` 下它不可见（要 POSIX 特性宏），自定一个 ✓ */\n"
        "    if (len <= 0 || len >= (int64_t)sizeof p) return -1;\n"
        "    memcpy(p, path, (size_t)len);\n"
        "    p[len] = 0;\n"
        "    int fd = open(p, O_RDONLY);\n"
        "    if (fd < 0) return -1;\n"
        "    struct stat st;\n"
        "    if (fstat(fd, &st) != 0) { close(fd); return -1; }\n"
        "    *out_size  = (int64_t)st.st_size;\n"
        "    *out_mtime = (int64_t)st.st_mtime;\n"
        "    *out_isdir = S_ISDIR(st.st_mode) ? 1 : 0;\n"
        "    return (int64_t)fd;\n"
        "}\n\n"
        "/* 非阻塞 socket 上的 sendfile：返回**这次**送出去多少（可能少于 n ⇒ 调用方补）。\n"
        " * 偏移由调用方给，于是 Range 与部分写都能续。 */\n"
        "int64_t extc_sendfile(int64_t out_fd, int64_t in_fd, int64_t off, int64_t n) {\n"
        "    off_t o = (off_t)off;\n"
        "    ssize_t r = sendfile((int)out_fd, (int)in_fd, &o, (size_t)n);\n"
        "    return (int64_t)r;\n"
        "}\n\n"
        "/* HTTP 日期：正确性交给 libc（`strftime`/`strptime` 是打过仗的），extC 只拿长度与秒数。 */\n"
        "int64_t extc_http_date(int64_t epoch, uint8_t *out) {\n"
        "    time_t t = (time_t)epoch;\n"
        "    struct tm tm;\n"
        "    if (!gmtime_r(&t, &tm)) return -1;\n"
        "    return (int64_t)strftime((char *)out, 64, \"%a, %d %b %Y %H:%M:%S GMT\", &tm);\n"
        "}\n\n"
        "int64_t extc_http_parse_date(uint8_t *s, int64_t len) {\n"
        "    char buf[64];\n"
        "    if (len <= 0 || len >= (int64_t)sizeof buf) return -1;\n"
        "    memcpy(buf, s, (size_t)len);\n"
        "    buf[len] = 0;\n"
        "    struct tm tm;\n"
        "    memset(&tm, 0, sizeof tm);\n"
        "    if (!strptime(buf, \"%a, %d %b %Y %H:%M:%S GMT\", &tm)) return -1;\n"
        "    return (int64_t)timegm(&tm);\n"
        "}\n\n"
        "int64_t extc_file_close(int64_t fd) { return (int64_t)close((int)fd); }\n");
}
