/* Access to the prelude text that tools/embed.c linked into the compiler.
 *
 * Nothing here knows what the prelude contains: this file only hands the byte array
 * to the loader.
 */

#include "prelude.h"

/* Generated by tools/embed.c into build/prelude_data.c. */
extern const unsigned char extc_prelude[];
extern const unsigned long extc_prelude_len;

/* Return the embedded prelude text.
 *
 * Params:
 *   len - receives the length in bytes; the text is not NUL-terminated
 *
 * Returns:
 *   A pointer to the byte array linked into the compiler. It lives in static storage
 *   for the whole run, so the caller must neither free it nor expect a terminator.
 */
const char *preludeSource(size_t *len) {
    *len = (size_t)extc_prelude_len;
    return (const char *)extc_prelude;
}
