/* Generated by the extC compiler -- do not edit by hand.
 * The generated C is deliberately boring: no macro tricks, no clever optimizations.
 * `#line` directives map the C compiler's errors back to the .extc source lines.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define EXTC_DYN_HANDLE_DEFINED 1
struct ExtcDynHandleS { int64_t pid, slot, gen, pgen; };
typedef struct ExtcDynHandleS ExtcDynHandle;

/* Every path that ends the process on purpose goes through here. A trap path is
 * the only code that still runs when a program dies, so this is where anything the
 * process has to give back is given back. Today that is the terminal: a program
 * that traps in raw mode would otherwise leave the user's shell unable to echo
 * what they type. The hook is installed by `extc_raw_enter` (emitted only when the
 * program uses the raw-terminal primitives) and cleared before it runs, so it
 * cannot run twice. */
static int32_t (*__extc_dying)(void);
#if defined(__GNUC__) || defined(__clang__)
#  define EXTC_NORETURN __attribute__((noreturn))
#else
#  define EXTC_NORETURN _Noreturn
#endif
EXTC_NORETURN static inline void extc_die(int code) {
    if (__extc_dying) { int32_t (*f)(void) = __extc_dying; __extc_dying = 0; (void)f(); }
    exit(code);
}
/* Every primitive below is `static inline`, and that is not a style choice:
 * without inlining, gcc at -O1 cannot see the body of a check, so it can neither
 * eliminate the check nor turn `i % 7` into a multiply and shift. Measured: the
 * remainder operator was 4.6x slower and a matrix multiply 1.5x slower; with
 * inlining both match C. */
/* Out-of-range trap; the position comes from the call site via `#line`. */
EXTC_NORETURN static inline void extc_trap(const char *file, int line, int64_t i, int64_t n) {
    fprintf(stderr, "%s:%d: trap: index %lld out of range (length %lld)\n",
            file, line, (long long)i, (long long)n);
    extc_die(1);
}
/* Arithmetic failures must be loud: division by zero, the overflowing division, and
 * an over-wide shift are all undefined behaviour in C. Each one traps with a
 * source position instead of computing a wrong answer or leaving UB behind. */
EXTC_NORETURN static inline void extc_trapMsg(const char *file, int line, const char *msg) {
    fprintf(stderr, "%s:%d: trap: %s\n", file, line, msg);
    extc_die(1);
}
#ifndef EXTC_REC_LIMIT
#define EXTC_REC_LIMIT 100000
#endif
static int64_t __extc_rec_depth = 0;
static inline void extc_rec_enter(const char *f, int l) {
    if (++__extc_rec_depth > EXTC_REC_LIMIT)
        extc_trapMsg(f, l, "recursion too deep (unbounded recursion?)");
}
static inline int64_t extc_divI(int64_t a, int64_t b, const char *f, int l) {
    if (b == 0) extc_trapMsg(f, l, "division by zero");
    if (a == INT64_MIN && b == -1) extc_trapMsg(f, l, "integer overflow in division");
    return a / b;
}
static inline int64_t extc_modI(int64_t a, int64_t b, const char *f, int l) {
    if (b == 0) extc_trapMsg(f, l, "division by zero");
    if (a == INT64_MIN && b == -1) extc_trapMsg(f, l, "integer overflow in division");
    return a % b;
}


/* Shifts: shifting by the width or more, or by a negative amount, is undefined
 * behaviour in C, so the count is checked and returned (evaluated once). */
static inline int64_t extc_shiftCount(int64_t b, int64_t w, const char *f, int l) {
    if (b < 0 || b >= w) extc_trapMsg(f, l, "shift count out of range");
    return b;
}
/* Checked index: the index is returned, so the caller evaluates it only once. */
static inline int64_t extc_checkedIndex(int64_t i, int64_t n, const char *file, int line) {
    if (i < 0 || i >= n) extc_trap(file, line, i, n);
    return i;
}
/* Checked slice: requires 0 <= lo <= hi <= n, and returns `lo`. */
static inline int64_t extc_checkedRange(int64_t lo, int64_t hi, int64_t n,
                          const char *file, int line) {
    if (lo < 0 || hi < lo || hi > n) {
        fprintf(stderr, "%s:%d: trap: slice %lld..%lld is out of range (length %lld)\n",
                file, line, (long long)lo, (long long)hi, (long long)n);
        extc_die(1);
    }
    return lo;
}

typedef struct extc_ablock { struct extc_ablock *prev; int64_t cap, used; char data[1]; } extc_ablock;
typedef struct extc_arena { extc_ablock *top; extc_ablock *spare; } extc_arena;
#ifndef EXTC_ARENA_SPARE_MAX
#define EXTC_ARENA_SPARE_MAX (1 << 20)
#endif
static inline void extc_arena_release(extc_arena *a) {
    while (a->top) {
        extc_ablock *p = a->top->prev;
        /* Always keep one block back. Guarding this with "the arena had more
         * than one block" looked like a saving and was the opposite: the
         * block that pays off is precisely the single-block arena of a tight
         * loop, and skipping it put the churn shape back to its old time
         * (measured: 139.9ms -> 389.9ms). */
        if (!a->spare && a->top->cap <= EXTC_ARENA_SPARE_MAX) {
            a->spare = a->top; a->spare->prev = NULL;
        } else {
            free(a->top);
        }
        a->top = p;
    }
}
static inline void extc_arena_destroy(extc_arena *a) {
    extc_arena_release(a);
    if (a->spare) { free(a->spare); a->spare = NULL; }
}
/* Explicit conversions: narrowing, sign change, or float-to-integer. A value that
 * does not fit traps, reporting the source position. */
static inline int64_t extc_narrowI(int64_t v, int64_t lo, int64_t hi, const char *f, int l) {
    if (v < lo || v > hi) extc_trapMsg(f, l, "value does not fit in the target type");
    return v;
}
static inline uint64_t extc_narrowU(uint64_t v, uint64_t hi, const char *f, int l) {
    if (v > hi) extc_trapMsg(f, l, "value does not fit in the target type");
    return v;
}

#if defined(__GNUC__) || defined(__clang__)
#define EXTC_INLINE static inline __attribute__((always_inline))
#else
#define EXTC_INLINE static inline
#endif
EXTC_INLINE void *extc_arena_alloc(extc_arena *a, int64_t n, const char *f, int l) {
    if (n <= 0) n = 1;
    n = (n + 7) & ~(int64_t)7;
    /* Adopt the spare only when the arena is empty.
     *
     * This is one test on a pointer that is NULL in the common case, which
     * matters: an allocation in a loop runs this code millions of times, and
     * an earlier version that asked 'is the spare big enough for n' on every
     * call cost about 20% more instructions over the whole program (measured
     * with callgrind on the rebuild shape) for no benefit at all -- the spare
     * is a whole block, so `cap >= n` is already true whenever the arena is
     * empty enough to want it. */
    if (!a->top && a->spare) { a->top = a->spare; a->spare = NULL; a->top->used = 0; }
    if (!a->top || a->top->cap - a->top->used < n) {
        int64_t cap = n > 4096 ? n : 4096;
        extc_ablock *b = (extc_ablock *)malloc(sizeof(extc_ablock) + (size_t)cap);
        if (!b) { fprintf(stderr, "%s:%d: trap: out of arena memory"
                        " (this allocation wanted %lld bytes)\n",
                        f, l, (long long)n); extc_die(1); }
        b->prev = a->top; b->cap = cap; b->used = 0;
        a->top = b;
    }
    {
        void *p = a->top->data + a->top->used;
        a->top->used += n;
        memset(p, 0, (size_t)n);   /* fresh allocations are always zeroed */
        return p;
    }
}

enum { io$ioError_readFailed = 0, io$ioError_lineTooLong = 1, io$ioError_writeFailed = 2, io$ioError_notATerminal = 3, io$ioError_closed = 4, io$ioError_destFull = 5 };

typedef struct unit unit;
typedef struct pcg32 pcg32;
typedef struct io$writer io$writer;
typedef struct io$reader io$reader;
typedef struct io$ostream io$ostream;
typedef struct io$istream io$istream;
typedef struct io$errStream io$errStream;
typedef struct pool$handle pool$handle;
typedef struct string$string string$string;
typedef struct rect rect;
typedef struct circle circle;
typedef struct tri tri;
typedef struct slice_u8 slice_u8;
typedef struct slice_i32 slice_i32;
typedef struct slice_i64 slice_i64;
typedef struct slice_pool$handle slice_pool$handle;
typedef struct array_65536_u8 array_65536_u8;
typedef struct array_24_u8 array_24_u8;
typedef struct array_200_u8 array_200_u8;
typedef struct varArray_i64 varArray_i64;
typedef struct pool$pool_Shape pool$pool_Shape;
typedef struct slice_Shape slice_Shape;
typedef struct io$ioError io$ioError;
typedef struct result_i64_io$ioError result_i64_io$ioError;
typedef struct result_bool_io$ioError result_bool_io$ioError;
typedef struct option_u8 option_u8;
typedef struct option_i64 option_i64;
typedef struct option_Shape option_Shape;

struct unit {
    char __extc_empty;
};

struct pcg32 {
    uint64_t state;
    uint64_t inc;
};

struct io$ostream {
    int32_t fd;
};

struct io$istream {
    int32_t fd;
};

struct io$errStream {
    char __extc_empty;
};

struct pool$handle {
    int32_t slot;
    int32_t gen;
    int64_t ep;
};

struct rect {
    int64_t w;
    int64_t h;
};

struct circle {
    int64_t r;
};

struct tri {
    int64_t b;
    int64_t h;
};

struct slice_u8 {
    uint8_t * data;
    int64_t len;
};

struct slice_i32 {
    int32_t * data;
    int64_t len;
};

struct slice_i64 {
    int64_t * data;
    int64_t len;
};

struct slice_pool$handle {
    pool$handle * data;
    int64_t len;
};

struct array_65536_u8 {
    uint8_t data[65536];
};

struct array_24_u8 {
    uint8_t data[24];
};

struct array_200_u8 {
    uint8_t data[200];
};

struct varArray_i64 {
    slice_i64 buf;
    int64_t len;
    int64_t cap;
};

struct slice_Shape {
    ExtcDynHandle * data;
    int64_t len;
};

struct io$ioError {
    int tag;
    union {
        struct { int32_t _0; } readFailed;
        struct { int64_t _0; } lineTooLong;
        struct { int32_t _0; } writeFailed;
        struct { int32_t _0; } notATerminal;
        struct { int32_t _0; } closed;
        struct { int64_t _0; } destFull;
    } u;
};

struct result_i64_io$ioError {
    int tag;
    union {
        struct { io$ioError _0; } failure;
        struct { int64_t _0; } success;
    } u;
};

struct result_bool_io$ioError {
    int tag;
    union {
        struct { io$ioError _0; } failure;
        struct { bool _0; } success;
    } u;
};

struct option_u8 {
    int tag;
    union {
        struct { uint8_t _0; } some;
    } u;
};

struct option_i64 {
    int tag;
    union {
        struct { int64_t _0; } some;
    } u;
};

struct option_Shape {
    int tag;
    union {
        struct { ExtcDynHandle _0; } some;
    } u;
};

struct io$writer {
    int32_t fd;
    slice_u8 buf;
    int64_t len;
};

struct io$reader {
    int32_t fd;
    slice_u8 chunk;
    int64_t len;
    int64_t pos;
};

struct string$string {
    slice_u8 buf;
    int64_t n;
    int64_t cap;
    int64_t pid;
    uint64_t pidGen;
};

struct pool$pool_Shape {
    slice_Shape vals;
    slice_i32 slots;
    slice_i64 ent;
    int64_t pid;
    uint64_t pidGen;
    int64_t epoch;
    int32_t cursor;
    int32_t holeHead;
    int64_t n;
    int64_t cap;
};

enum { result_i64_io$ioError_failure = 0, result_i64_io$ioError_success = 1 };
enum { result_bool_io$ioError_failure = 0, result_bool_io$ioError_success = 1 };
enum { option_u8_none = 0, option_u8_some = 1 };
enum { option_i64_none = 0, option_i64_some = 1 };
enum { option_Shape_none = 0, option_Shape_some = 1 };
static int64_t io$I64_MAX = 9223372036854775807;
static io$ostream io$cout = {.fd = 1};
static array_65536_u8 io$IN_BUF;
static int64_t io$IN_LEN = 0;
static int64_t io$IN_POS = 0;
static bool io$IN_BAD = false;
static io$istream io$cin = {.fd = 0};
static slice_u8 io$DIGITS = (slice_u8){ .data = (uint8_t *)"00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899", .len = sizeof("00010203040506070809101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899") - 1 };
static array_24_u8 io$FMT;
static array_200_u8 io$PAIRS;
static bool io$PAIRS_READY = false;
static int64_t pool$HANDLE_EPOCH_BITS = 32;

static varArray_i64 varArray_i64_withCap(int64_t cap, extc_arena *__extc_home);
static void varArray_i64_grow(varArray_i64 * self, extc_arena *__extc_home);
static void varArray_i64_push(varArray_i64 * self, int64_t v, extc_arena *__extc_home);
static option_i64 varArray_i64_get(varArray_i64 * self, int64_t i);
EXTC_INLINE int64_t pool$pool_Shape_pLow(int64_t e);
EXTC_INLINE int64_t pool$pool_Shape_pDense(int64_t e);
EXTC_INLINE int64_t pool$pool_Shape_pGen(int64_t e);
EXTC_INLINE int64_t pool$pool_Shape_pPack(int64_t gen, int64_t low);
EXTC_INLINE int64_t pool$pool_Shape_pEpMask(void);
EXTC_INLINE int64_t pool$pool_Shape_pEp(int64_t v);
EXTC_INLINE bool pool$pool_Shape_pFree(pool$pool_Shape * self, int64_t e);
static pool$pool_Shape pool$pool_Shape_withCap(int64_t n, int64_t __extc_home_zone);
static pool$pool_Shape pool$pool_Shape_withParent(int64_t parent, int64_t n, int64_t __extc_home_zone);
EXTC_INLINE int64_t pool$pool_Shape_len(pool$pool_Shape * self);
static bool pool$pool_Shape_pLive(pool$pool_Shape * self, pool$handle h);
static bool pool$pool_Shape_contains(pool$pool_Shape * self, pool$handle h);
static option_Shape pool$pool_Shape_get(pool$pool_Shape * self, pool$handle h);
static pool$handle pool$pool_Shape_insert(pool$pool_Shape * self, ExtcDynHandle v);
static bool pool$pool_Shape_remove(pool$pool_Shape * self, pool$handle h);
static bool pool$pool_Shape_pStaleSelf(pool$pool_Shape * self);
static void pool$pool_Shape_pPoisonSelf(pool$pool_Shape * self);
static int64_t pool$pool_Shape_bytesOf(pool$pool_Shape * self);
EXTC_INLINE ExtcDynHandle pool$pool_Shape_atDense(pool$pool_Shape * self, int64_t i);
EXTC_INLINE pool$handle pool$pool_Shape_handleAtDense(pool$pool_Shape * self, int64_t i);
static void pool$pool_Shape_grow(pool$pool_Shape * self);









EXTC_INLINE io$ostream io$ostream_shl_i64(io$ostream * self, int64_t v);
EXTC_INLINE io$ostream io$ostream_shl_slice_u8(io$ostream * self, slice_u8 v);
EXTC_INLINE io$istream io$istream_shr_mut_Ref_i64(io$istream * self, int64_t * v);
static string$string string$string_new(int64_t c, int64_t __extc_home_zone);
static slice_u8 string$string_toSlice(string$string * self, extc_arena *__extc_home);




static void string$string_grow(string$string * self);
static void string$string_push(string$string * self, uint8_t b);
static void string$string_append(string$string * self, slice_u8 s);
static bool string$string_pStale(string$string * self);
static void string$string_pPoison(string$string * self);
static int64_t rect_area(rect * self);
static int64_t circle_area(circle * self);
static int64_t tri_area(tri * self);
int64_t read(int32_t fd, uint8_t * buf, int64_t n);
int64_t write(int32_t fd, uint8_t * buf, int64_t n);
void extc_cout_put(uint8_t * p, int64_t n);
void extc_cout_flush(void);
void extc_cout_f64(double v);
EXTC_INLINE result_i64_io$ioError io$fillState(int32_t fd, slice_u8 buf, int64_t * len, int64_t * pos);
EXTC_INLINE bool io$accDigit(int64_t * v, int64_t * nd, int64_t d);
EXTC_INLINE result_i64_io$ioError io$nextI64State(int32_t fd, slice_u8 buf, int64_t * len, int64_t * pos, bool * got);
EXTC_INLINE bool io$isSpaceByte(int64_t b);


EXTC_INLINE void io$pairsReady(void);
EXTC_INLINE int64_t io$fmtI64Fast(int64_t v);


int64_t extc_pool_new(int64_t parent);
void extc_pool_drop(int64_t rid);
void extc_pool_reset(int64_t rid);
uint64_t extc_pool_generation(int64_t rid);
int64_t extc_pool_bytes(int64_t rid);
static string$string string$withCap(int64_t c, int64_t __extc_home_zone);
static int64_t minArea(void);
static void pushI64(string$string * s, int64_t v);
static slice_u8 kindName(int64_t kind);
static string$string line(int64_t idx, int64_t kind, int64_t area, int64_t __extc_home_zone);
int main(void);

struct extc_vt$Shape_t { int64_t (*area)(void *); };
static const struct extc_vt$Shape_t extc_vt$Shape$rect;
static const struct extc_vt$Shape_t extc_vt$Shape$circle;
static const struct extc_vt$Shape_t extc_vt$Shape$tri;
/* Buffered console output (ruling 90). The buffer lives in the runtime rather than
 * in the library so that the flush has a home the generator can call; the library
 * formats and calls `extc_cout_put`, which the C compiler inlines into it (same
 * translation unit, small body). */
static uint8_t extc_cout_buf[1 << 18];
static int64_t extc_cout_len = 0;
void extc_cout_flush(void);
void extc_cout_put(uint8_t *p, int64_t n);
void extc_cout_f64(double v);
void extc_cout_flush(void) {
    if (extc_cout_len <= 0) return;
    /* Through stdio: `unistd.h` cannot be included here (the library declares
     * `read`/`write` with its own prototypes, and the two clash). stdio also keeps
     * the order with the deprecated print path and flushes at exit by itself. */
    fwrite(extc_cout_buf, 1, (size_t)extc_cout_len, stdout);
    extc_cout_len = 0;
}
void extc_cout_put(uint8_t *p, int64_t n) {
    if (n <= 0) return;
    if (extc_cout_len + n > (int64_t)sizeof extc_cout_buf) extc_cout_flush();
    memcpy(extc_cout_buf + extc_cout_len, p, (size_t)n);
    extc_cout_len += n;
}
/* ---- pool registry (POOLS.md) ----
 * A pool is an index here, never a value: the library hands out `{ index, generation }`,
 * and dropping bumps the generation, so a handle that outlived its pool fails a check
 * instead of reading freed memory.
 *
 * The picture: the arena is a chain of blocks and nothing else - it is where memory
 * comes from. A pool is a structure of its own: it links what it holds (nested pools)
 * as a side chain beside the arena; the memory its containers use is its OWN plate (a chain
 * of blocks it owns, and can give back when a buffer is replaced). A zone is the head of one such
 * side chain - a virtual grouping, one per place, holding the pools created there. It
 * is deliberately not embedded in the arena's stack: leaving a place has to enumerate
 * the zone's own chain, and a block rollback must not be able to tear that structure
 * out from under it.
 *
 * `extc_pool_zoneLeaveTo(mark)` pops to a mark rather than popping blindly, so early
 * exits (`return`, `break`, `continue`) cannot leave the stack unbalanced: a leave is
 * always expressed as "back to the depth this place started at".
 *
 * Emitted only for a program that declares a pool extern. */
typedef struct ExtcBlock { struct ExtcBlock *next; int64_t size; } ExtcBlock;
typedef struct ExtcPool {
    uint64_t generation;
    int64_t  parent;        /* parent pool, or -1 for a root of its zone */
    int64_t  zone;          /* the zone (place) that owns it */
    int64_t  firstChild;    /* nested pools: a container of containers */
    int64_t  nextSibling;   /* the parent's child list */
    int64_t  zoneNext;      /* the zone's list of pool trees (the side chain) */
    int64_t  freeNext;      /* the free list of slots */
    int64_t  live;
    int64_t  color;        /* 出生时它那个 zone 的颜色（染色：一次翻色作废整棵树）*/
    ExtcBlock *blocks;     /* THE PLATE: the blocks this pool owns (never borrowed) */
    int64_t  bytes;        /* what those blocks hold right now */
} ExtcPool;
typedef struct ExtcZone { int64_t firstPool, parent; int64_t color; } ExtcZone;
static ExtcPool *extc_pools        = NULL;
static int64_t   extc_poolCap      = 0;
static int64_t   extc_poolLiveN    = 0;
static int64_t   extc_poolFreeHead = -1;
static int64_t   extc_poolBytesAll = 0;   /* live bytes over all pools (evidence) */
/* The pool MODE (0 = container plate, 1 = object table) lives in a side table, not in
 * ExtcPool: the struct is 88 bytes and it is touched once per container operation, so an
 * extra field would grow it to 96 and cost one extra address instruction on every access
 * (measured: +11,000,000 instructions on one bench, i.e. one per touch). The mode is only
 * read on the cold paths (give / resize / reset / new_table), so a byte array is free. */
static uint8_t  *extc_poolKind     = NULL;
static int64_t   extc_poolKindCap  = 0;
/* 色宽：3 位。位宽**只是检测强度**（命中 1/8），不参与正确性 —— 色只做否决，
 * 活性权威永远是 n / 空洞链 / 世代（POOLS.md 7.4 第 2 条与 7.6 第 4 条）。 */
#ifndef EXTC_ZONE_COLOR_BITS
#define EXTC_ZONE_COLOR_BITS 3
#endif
static ExtcZone *extc_zones        = NULL;
static int64_t   extc_zoneCap      = 0;
static int64_t   extc_zoneTop      = -1;
int64_t extc_pool_live(void) { return extc_poolLiveN; }
int64_t extc_pool_capacity(void) { return extc_poolCap; }
int64_t extc_pool_zoneDepth(void) { return extc_zoneTop + 1; }
/* Entering a place: push the head of a side chain and hand back its mark. */
int64_t extc_pool_zoneEnter(void) {
    int64_t id = extc_zoneTop + 1;
    if (id >= extc_zoneCap) {
        int64_t want = extc_zoneCap ? extc_zoneCap * 2 : 64;
        ExtcZone *grown = (ExtcZone *)realloc(extc_zones, (size_t)want * sizeof *grown);
        if (!grown) return -1;
        extc_zones = grown; extc_zoneCap = want;
    }
    /* 染色：**翻一位**（加一取模）。同一个下标是循环体每轮复用的那个地方，所以上一轮
     * 出生在这儿的池，颜色必然对不上 ⇒ 一次比较就作废整棵树，一个槽都不用走。
     * 全新的一格（realloc 之后初值 0）也从 1 开始，与「从未用过」的 0 区分开。 */
    extc_zones[id].color = (extc_zones[id].color + 1) & ((1 << EXTC_ZONE_COLOR_BITS) - 1);
    if (extc_zones[id].color == 0) extc_zones[id].color = 1;
    extc_zones[id].firstPool = -1;
    extc_zones[id].parent    = extc_zoneTop;
    extc_zoneTop = id;
    return id;
}
static void extc_pool_releaseBlocks(ExtcPool *r) {
    ExtcBlock *b = r->blocks;
    while (b) { ExtcBlock *next = b->next; extc_poolBytesAll -= b->size; free(b); b = next; }
    r->blocks = NULL; r->bytes = 0;
}
static void extc_pool_freeSelf(int64_t rid) {
    ExtcPool *r = &extc_pools[rid];
    /* The plate goes back here, and this is the real release: the arena only ever takes
     * whole blocks back at a place boundary, the pool hands its own memory back at once. */
    extc_pool_releaseBlocks(r);
    r->live = 0; r->parent = -1; r->firstChild = -1;
    r->freeNext = extc_poolFreeHead;
    extc_poolFreeHead = rid;
    extc_poolLiveN--;
}
static void extc_pool_unlinkZone(int64_t rid) {
    int64_t zi = extc_pools[rid].zone;
    if (zi < 0) return;
    {
        int64_t *link = &extc_zones[zi].firstPool;
        while (*link >= 0) {
            if (*link == rid) { *link = extc_pools[rid].zoneNext; break; }
            link = &extc_pools[*link].zoneNext;
        }
    }
}
void extc_pool_drop(int64_t rid) {
    int64_t child, parent;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return;
    child = extc_pools[rid].firstChild;
    while (child >= 0) {
        int64_t next = extc_pools[child].nextSibling;
        extc_pool_drop(child);
        child = next;
    }
    parent = extc_pools[rid].parent;
    if (parent >= 0) {
        int64_t *link = &extc_pools[parent].firstChild;
        while (*link >= 0) {
            if (*link == rid) { *link = extc_pools[rid].nextSibling; break; }
            link = &extc_pools[*link].nextSibling;
        }
    }
    /* A pool is on the zone chain whether or not it has a parent, so dropping it
     * always has to leave that chain -- a stale link would be followed by the next
     * zone sweep, and the record may already belong to somebody else. */
    extc_pool_unlinkZone(rid);
    extc_pool_freeSelf(rid);
}
/* A pool is created with its container, inside some place; `parent` is another pool when
 * the container nests one, -1 otherwise. No arena and no level number is passed: the pool
 * starts with an empty plate and takes blocks of its own as the container grows. */
/* THE PROMOTION HOOK (POOLS.md 3.1 / MEMORY-SAFETY 3.1).
 *
 * `zone` names the place this pool is BORN in -- normally the current top, which is what
 * `extc_pool_new` passes. The arena has the same door: a function that hands its allocation
 * to the caller's place takes a hidden `__extc_home` arena, so `new` inside it lands where
 * the value ends up. A container built inside a loop body and then stored into something
 * that outlives the loop needs exactly that: without it its plate dies with the iteration
 * (measured: `vector<vector<i32>>` pushes three inner vectors, and after the loop
 * `extc_pool_live()` is back to 1 -- all three inner pools are gone while the outer plate
 * still holds values pointing at them; ASan says heap-use-after-free).
 *
 * The zone index is a plain integer and equals depth - 1 (`zoneEnter` hands out
 * `extc_zoneTop + 1`), so naming a place costs nothing and never dangles: the target zone
 * is on the stack whenever a promoted construction runs. */
int64_t extc_pool_new_at(int64_t parent, int64_t zi) {
    int64_t idx;
    ExtcPool *r;
    if (zi < 0 || zi > extc_zoneTop) return -1;   /* the named place is not on the stack */
    if (extc_poolFreeHead >= 0) {
        idx = extc_poolFreeHead;
        extc_poolFreeHead = extc_pools[idx].freeNext;
    } else {
        int64_t want = extc_poolCap ? extc_poolCap * 2 : 64, i;
        ExtcPool *grown = (ExtcPool *)realloc(extc_pools, (size_t)want * sizeof *grown);
        if (!grown) return -1;
        for (i = extc_poolCap; i < want; i++) {
            grown[i].generation = 0; grown[i].parent = -1; grown[i].zone = -1;
            grown[i].firstChild = -1; grown[i].nextSibling = -1;
            grown[i].zoneNext = -1; grown[i].freeNext = -1; grown[i].live = 0; grown[i].blocks = NULL; grown[i].bytes = 0;
        }
        {
            uint8_t *gk = (uint8_t *)realloc(extc_poolKind, (size_t)want);
            if (!gk) { fprintf(stderr, "trap: out of pool memory (kind table)\n"); extc_die(1); }
            memset(gk + extc_poolKindCap, 0, (size_t)(want - extc_poolKindCap));
            extc_poolKind = gk; extc_poolKindCap = want;
        }
        extc_pools = grown; idx = extc_poolCap; extc_poolCap = want;
    }
    r = &extc_pools[idx];
    if (r->live) return -1;
    r->generation++;
    r->live = 1; r->parent = parent; r->zone = zi;
    r->color = extc_zones[zi].color;   /* 出生色：与 zone 当前色不符 ⇒ 那个地方死过 */
    r->firstChild = -1; r->nextSibling = -1; r->zoneNext = -1;
    r->blocks = NULL; r->bytes = 0;
    /* TWO CHAINS, attached separately (POOLS.md 7.7). The zone root chain is LIFETIME: a place
     * releases everything in it, and it has to see every pool, nested or not. The parent
     * chain is LOGICAL: dropping a container takes the containers nested inside it.
     * Attaching only the parent chain would hide a nested pool from its own place, so a
     * pool created in a deeper block would outlive it. */
    r->zoneNext = extc_zones[zi].firstPool;
    extc_zones[zi].firstPool = idx;
    if (parent >= 0) {
        r->nextSibling = extc_pools[parent].firstChild;
        extc_pools[parent].firstChild = idx;
    }
    extc_poolLiveN++;
    return idx;
}
/* 不放宽时的常规入口：生在当前顶上 */
int64_t extc_pool_new(int64_t parent) { return extc_pool_new_at(parent, extc_zoneTop); }
/* An OBJECT TABLE: same substrate, stricter contract (dyn's kind of pool).
 * Append-only: a block may never be replaced or given back, because an element handle
 * (`{pool, idx, gen}`) would silently start pointing at something else -- the pool stays
 * live and its generation does not move. Deletion is a tombstone, not a free. */
int64_t extc_pool_new_table(int64_t parent) {
    int64_t rid = extc_pool_new(parent);
    if (rid >= 0 && rid < extc_poolKindCap) extc_poolKind[rid] = 1;
    return rid;
}
int64_t extc_pool_kind(int64_t rid) {
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return -1;
    return (rid < extc_poolKindCap) ? (int64_t)extc_poolKind[rid] : 0;
}
uint64_t extc_pool_generation(int64_t rid) {
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return 0;
    return extc_pools[rid].generation;
}
/* Keep the pool, mark its slots reusable: the nested tree is walked and dropped. The
 * memory stays where it is (the arena releases it at the end of the place), so `reset`
 * is about reuse, not about returning memory - which is what makes it cheap to call. */
void extc_pool_reset(int64_t rid) {
    int64_t child;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return;
    child = extc_pools[rid].firstChild;
    while (child >= 0) {
        int64_t next = extc_pools[child].nextSibling;
        extc_pool_drop(child);
        child = next;
    }
    extc_pools[rid].firstChild = -1;
    /* INV-G: resetting KEEPS the pool alive and marks its slots reusable, so every handle
     * that pointed at one of those slots must stop validating -- otherwise it goes on
     * pointing at whatever takes the slot next. One line, and it is the whole difference
     * between "stale means trap" and "stale means somebody else's object". */
    extc_pools[rid].generation++;
}
/* Leaving a place: drop every zone from the top down to `mark` (the depth this place
 * started at). Expressed as a mark rather than one pop, so a path that skipped a leave
 * still ends up balanced. */
void extc_pool_zoneLeaveTo(int64_t mark) {
    while (extc_zoneTop >= mark && extc_zoneTop >= 0) {
        int64_t zi = extc_zoneTop;
        int64_t rid = extc_zones[zi].firstPool;
        while (rid >= 0) {
            int64_t next = extc_pools[rid].zoneNext;
            extc_pool_drop(rid);
            rid = next;
        }
        extc_zoneTop = extc_zones[zi].parent;
    }
}
/* ---- the plate: a pool's own memory (POOLS.md 2.1, PLAN #85) ----
 *
 * The container asks for a block here, not for arena memory, and gives the old block back
 * when it replaces it. That is the whole reason a doubling buffer no longer leaves every
 * old generation behind (the 9,900 KB reading in POOLS.md 1): the arena can only take whole
 * blocks back at a place boundary, a pool plate takes a block back the moment it is free.
 *
 * Every block is zeroed on the way out, so a fresh allocation still reads as zero -- the
 * promise the language makes about `new`, kept here without the arena. */
void *extc_pool_take(int64_t rid, int64_t bytes) {
    ExtcBlock *b;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return NULL;
    if (bytes <= 0) bytes = 1;
    b = (ExtcBlock *)malloc(sizeof(ExtcBlock) + (size_t)bytes);
    if (!b) { fprintf(stderr, "trap: out of pool memory (this allocation wanted %lld bytes)\n",
                      (long long)bytes); extc_die(1); }
    memset((void *)(b + 1), 0, (size_t)bytes);
    b->next  = extc_pools[rid].blocks;
    b->size  = bytes;
    extc_pools[rid].blocks  = b;
    extc_pools[rid].bytes  += bytes;
    extc_poolBytesAll      += bytes;
    return (void *)(b + 1);
}
/* Give one block back. The block is found by its address -- the caller holds a view, not a
 * block id -- and the walk is over this pool's own chain, which is short: a container that
 * grows by 1.5x has one live block plus whatever it has not replaced yet. */
/* 与 `take` 相同，只是**不清零**：给「马上就会被整片写掉」的那些块用（池自己的槽表尤其如此 ——
 * 一张全新的表在 `pFree` 的判据下天然全空闲，一个字节都不必写，连页都不必碰）。
 * 用户可见的内存不走这条路：`new T[n]` 的「新分配读作 0」是语言承诺，那条路照旧清零。 */
void *extc_pool_take_raw(int64_t rid, int64_t bytes) {
    ExtcBlock *b;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return NULL;
    if (bytes <= 0) bytes = 1;
    b = (ExtcBlock *)malloc(sizeof(ExtcBlock) + (size_t)bytes);
    if (!b) { fprintf(stderr, "trap: out of pool memory (this allocation wanted %lld bytes)\n",
                      (long long)bytes); extc_die(1); }
    /* **金丝雀**（判据专用，见 tests/pool/run.sh）：把 raw 块填成 0xAA ⇒ 任何「先读后写」的
     * raw 列都当场现形。选 0xAA 有两个理由：① 一眼认得出（不是零）；② 池自己的簿记也走这条
     * 路，而 `pFree` 的判据是 `lo == 0 || lo > cap` —— 0xAAAAAAAA 远大于 cap ⇒ 仍读作空闲。
     * 只有 `-DEXTC_POISON_RAW=1` 编译时才存在，正常产物零开销。 */
#ifdef EXTC_POISON_RAW
    memset((void *)(b + 1), 0xAA, (size_t)bytes);
#endif
    b->next  = extc_pools[rid].blocks;
    b->size  = bytes;
    extc_pools[rid].blocks  = b;
    extc_pools[rid].bytes  += bytes;
    extc_poolBytesAll      += bytes;
    return (void *)(b + 1);
}
int64_t extc_pool_give(int64_t rid, void *p) {
    ExtcBlock **link;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live || !p) return 0;
    if (rid < extc_poolKindCap && extc_poolKind[rid] != 0) {
        fprintf(stderr, "trap: this pool is an object table: a block may not be given back");
        fprintf(stderr, " (an element handle into it would go on pointing at freed memory)\n");
        extc_die(1);
    }
    link = &extc_pools[rid].blocks;
    while (*link) {
        ExtcBlock *b = *link;
        if ((void *)(b + 1) == p) {
            *link = b->next;
            extc_pools[rid].bytes -= b->size;
            extc_poolBytesAll     -= b->size;
            free(b);
            return 1;
        }
        link = &b->next;
    }
    return 0;
}
/* 染色那一层：这个池的出生色 vs 它那个 zone 现在的色。
 * 不等 ⇒ **一定**死过（那个地方退出过）；相等不保证活（位宽会绕回、垃圾内存会碰巧命中），
 * 所以它只做否决，活性仍看 n / 空洞链 / 世代（POOLS.md 7.6）。 */
int64_t extc_pool_rowColor(int64_t rid) {
    int64_t zi;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return -1;
    zi = extc_pools[rid].zone;
    if (zi < 0 || zi > extc_zoneTop) return -1;
    return extc_zones[zi].color;
}
int64_t extc_pool_birthColor(int64_t rid) {
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return -1;
    return extc_pools[rid].color;
}
int64_t extc_pool_bytes(int64_t rid) {
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live) return 0;
    return extc_pools[rid].bytes;
}
int64_t extc_pool_bytesLive(void) { return extc_poolBytesAll; }
/* Grow or shrink one block, in place when the allocator can. `grow` uses this instead of
 * take + copy + give, and the reason is the peak: with a copy, the old and the new block
 * are both alive for the length of the copy, which measured 1.9x the live size (15,052 KB
 * for an 8 MB vector); growing in place stays near it. Bytes added at the end are zeroed,
 * so an element that was never written still reads as zero, as everywhere else. */
void *extc_pool_resize(int64_t rid, void *p, int64_t bytes) {
    ExtcBlock **link;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live || !p) return NULL;
    if (rid < extc_poolKindCap && extc_poolKind[rid] != 0) {
        fprintf(stderr, "trap: this pool is an object table: a block may not be resized in place");
        fprintf(stderr, " (realloc may move it, and element handles would dangle)\n");
        extc_die(1);
    }
    if (bytes <= 0) bytes = 1;
    link = &extc_pools[rid].blocks;
    while (*link) {
        ExtcBlock *b = *link;
        if ((void *)(b + 1) == p) {
            int64_t old = b->size;
            ExtcBlock *nb = (ExtcBlock *)realloc(b, sizeof(ExtcBlock) + (size_t)bytes);
            if (!nb) { fprintf(stderr, "trap: out of pool memory (this resize wanted %lld bytes)\n",
                              (long long)bytes); extc_die(1); }
            if (bytes > old) memset((char *)(nb + 1) + old, 0, (size_t)(bytes - old));
            nb->size = bytes;
            *link    = nb;
            extc_pools[rid].bytes += bytes - old;
            extc_poolBytesAll     += bytes - old;
            return (void *)(nb + 1);
        }
        link = &b->next;
    }
    return NULL;
}
/* 与 `resize` 相同，只是新长出来那一段**不清零**（理由见 pools.c）。
 * `Raw` 只表示**不清零**，不表示放弃检查：对象表模式下它同样拒绝原地搬家 ——
 * 搬家与否跟清不清零是正交的两件事（见 `extc_pool_resize` 的守卫）。 */
void *extc_pool_resize_raw(int64_t rid, void *p, int64_t bytes) {
    ExtcBlock **link;
    if (rid < 0 || rid >= extc_poolCap || !extc_pools[rid].live || !p) return NULL;
    if (rid < extc_poolKindCap && extc_poolKind[rid] != 0) {
        fprintf(stderr, "trap: this pool is an object table: a block may not be resized in place");
        fprintf(stderr, " (realloc may move it, and element handles would dangle)\n");
        extc_die(1);
    }
    if (bytes <= 0) bytes = 1;
    link = &extc_pools[rid].blocks;
    while (*link) {
        ExtcBlock *b = *link;
        if ((void *)(b + 1) == p) {
            int64_t old = b->size;
            ExtcBlock *nb = (ExtcBlock *)realloc(b, sizeof(ExtcBlock) + (size_t)bytes);
            if (!nb) { fprintf(stderr, "trap: out of pool memory (this resize wanted %lld bytes)\n",
                              (long long)bytes); extc_die(1); }
#ifdef EXTC_POISON_RAW
            if (bytes > old) memset((char *)(nb + 1) + old, 0xAA, (size_t)(bytes - old));
#endif
            nb->size = bytes;
            *link    = nb;
            extc_pools[rid].bytes += bytes - old;
            extc_poolBytesAll     += bytes - old;
            return (void *)(nb + 1);
        }
        link = &b->next;
    }
    return NULL;
}
#ifndef EXTC_DYN_HANDLE_DEFINED
#define EXTC_DYN_HANDLE_DEFINED 1
/* Tagged, and four fields: `gen` is the SLOT generation (recycling) and `pgen` the POOL generation
 * (a reset, or the place that owned it going away) -- two independent ways to become stale, both
 * checked before dispatch. The tag matters: emitted twice, and two anonymous structs differ. */
struct ExtcDynHandleS { int64_t pid, slot, gen, pgen; };
typedef struct ExtcDynHandleS ExtcDynHandle;
#endif
typedef struct { int64_t pid, pgen, gen, next; void *addr; const void *vt; } ExtcDynSlot;
static ExtcDynSlot *extc_dynSlots   = NULL;
static int64_t      extc_dynCap     = 0;
static int64_t      extc_dynN       = 0;
static int64_t      extc_dynFree    = -1;
static int64_t      extc_dynLiveN   = 0;
static int64_t     *extc_dynPoolOf  = NULL;
static int64_t      extc_dynPoolCap = 0;
EXTC_NORETURN static void extc_dynTrap(const char *file, int line, const char *why) {
    fprintf(stderr, "%s:%d: trap: %s\
", file, line, why);
    extc_die(1);
}
/* A slot is dead when its pool is gone, OR when its pool id was taken by a new pool: a loop body's
 * zone index is reused every iteration and so is the pool id, so "the id names a live object table"
 * is not enough -- the generation the slot was born with has to match as well. */
static void extc_dynSweep(void) {
    int64_t i;
    for (i = 0; i < extc_dynN; i++) {
        int64_t pid = extc_dynSlots[i].pid;
        if (pid < 0) continue;
        if (extc_pool_kind(pid) != 1 ||
            (int64_t)extc_pool_generation(pid) != extc_dynSlots[i].pgen) {
            extc_dynSlots[i].gen++;
            extc_dynSlots[i].pid = -1;
            extc_dynSlots[i].next = extc_dynFree;
            extc_dynFree = i;
            extc_dynLiveN--;
        }
    }
}
int64_t extc_dyn_liveSlots(void) { return extc_dynLiveN; }
ExtcDynHandle extc_dyn_put(const void *payload, int64_t size, const void *vt) {
    ExtcDynHandle h;
    ExtcDynSlot *s;
    int64_t zi = extc_zoneTop, pid, slot;
    if (zi < 0) extc_dynTrap("?", 0, "a `dyn` value needs a place to live in");
    if (zi >= extc_dynPoolCap) {
        int64_t want = extc_dynPoolCap ? extc_dynPoolCap * 2 : 64;
        int64_t *grown = (int64_t *)realloc(extc_dynPoolOf, (size_t)want * sizeof *grown);
        if (!grown) extc_dynTrap("?", 0, "out of pool memory (dyn zone table)");
        for (int64_t i = extc_dynPoolCap; i < want; i++) grown[i] = -1;
        extc_dynPoolOf = grown; extc_dynPoolCap = want;
    }
    pid = extc_dynPoolOf[zi];
    if (pid < 0 || extc_pool_kind(pid) != 1 || extc_pool_generation(pid) == 0) {
        pid = extc_pool_new_table(-1);
        if (pid < 0) extc_dynTrap("?", 0, "out of pool memory (dyn)");
        extc_dynPoolOf[zi] = pid;
    }
    if (extc_dynFree < 0 && extc_dynN >= extc_dynCap) extc_dynSweep();
    if (extc_dynFree >= 0) {
        slot = extc_dynFree;
        extc_dynFree = extc_dynSlots[slot].next;
    } else {
        if (extc_dynN >= extc_dynCap) {
            int64_t want = extc_dynCap ? extc_dynCap * 2 : 64;
            ExtcDynSlot *grown = (ExtcDynSlot *)realloc(extc_dynSlots, (size_t)want * sizeof *grown);
            if (!grown) extc_dynTrap("?", 0, "out of pool memory (dyn slots)");
            for (int64_t i = extc_dynCap; i < want; i++) {
                grown[i].pid = -1; grown[i].pgen = 0; grown[i].gen = 0; grown[i].next = -1;
                grown[i].addr = NULL; grown[i].vt = NULL;
            }
            extc_dynSlots = grown; extc_dynCap = want;
        }
        slot = extc_dynN++;
    }
    s = &extc_dynSlots[slot];
    s->pid  = pid;
    s->pgen = (int64_t)extc_pool_generation(pid);
    s->addr = extc_pool_take(pid, size);
    s->vt   = vt;
    extc_dynLiveN++;
    if (!s->addr) extc_dynTrap("?", 0, "out of pool memory (dyn payload)");
    if (payload) memcpy(s->addr, payload, (size_t)size);
    h.pid = pid; h.slot = slot; h.gen = s->gen; h.pgen = s->pgen;
    return h;
}
EXTC_INLINE ExtcDynSlot *extc_dyn_slot(ExtcDynHandle h, const char *file, int line) {
    ExtcDynSlot *s;
    if (h.slot < 0 || h.slot >= extc_dynN) extc_dynTrap(file, line, "stale `dyn` value");
    s = &extc_dynSlots[h.slot];
    if (s->pid < 0)                  extc_dynTrap(file, line, "stale `dyn` value (slot recycled)");
    if (s->pid != h.pid)             extc_dynTrap(file, line, "stale `dyn` value");
    if (s->gen != h.gen)             extc_dynTrap(file, line, "stale `dyn` value (slot recycled)");
    if (extc_pool_kind(h.pid) != 1)  extc_dynTrap(file, line, "stale `dyn` value");
    if ((int64_t)extc_pool_generation(h.pid) != h.pgen)
        extc_dynTrap(file, line, "stale `dyn` value (its pool was reset, or its place is gone)");
    return s;
}
static slice_u8 extc_slice_array_24_u8(array_24_u8 *a, int64_t lo, int64_t hi,
                       const char *f, int ln) {
    int64_t s = extc_checkedRange(lo, hi, 24, f, ln);
    return (slice_u8){ .data = &a->data[s], .len = hi - lo };
}
static slice_u8 extc_slice_slice_u8(slice_u8 v, int64_t lo, int64_t hi,
                       const char *f, int ln) {
    int64_t s = extc_checkedRange(lo, hi, v.len, f, ln);
    return (slice_u8){ .data = v.data + s, .len = hi - lo };
}
static inline int64_t *slice_i64_index(slice_i64 v, int64_t i, const char *file, int line) {
    if (i < 0 || i >= v.len) extc_trap(file, line, i, v.len);
    return &v.data[i];
}

static inline ExtcDynHandle *slice_Shape_index(slice_Shape v, int64_t i, const char *file, int line) {
    if (i < 0 || i >= v.len) extc_trap(file, line, i, v.len);
    return &v.data[i];
}

static inline int32_t *slice_i32_index(slice_i32 v, int64_t i, const char *file, int line) {
    if (i < 0 || i >= v.len) extc_trap(file, line, i, v.len);
    return &v.data[i];
}

static inline uint8_t *slice_u8_index(slice_u8 v, int64_t i, const char *file, int line) {
    if (i < 0 || i >= v.len) extc_trap(file, line, i, v.len);
    return &v.data[i];
}

static inline int64_t slice_u8_copy(slice_u8 d, slice_u8 s, int64_t n, const char *file, int line) {
    if (n < 0 || n > d.len || n > s.len)
        extc_trapMsg(file, line, "copyInto: the count is beyond a slice length");
    if (n > 0) memmove((void *)d.data, (const void *)s.data, (size_t)n * sizeof(uint8_t));
    return n;
}

static varArray_i64 varArray_i64_withCap(int64_t cap, extc_arena *__extc_home) {
    extc_arena __extc_a[3] = {0};
    varArray_i64 __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    if (cap < 0) {
        extc_arena_release(&__extc_a[2]);
        cap = 0;
        extc_arena_release(&__extc_a[2]);
    }
    varArray_i64 v = (varArray_i64){.buf = (slice_i64){ .data = (int64_t *)extc_arena_alloc(&(*__extc_home), (int64_t)(cap) * (int64_t)sizeof(int64_t), "examples/tour-plots.extc", 164), .len = (int64_t)(cap) }, .len = 0, .cap = cap};
    __extc_ret_v = v;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return __extc_ret_v;
}

static void varArray_i64_grow(varArray_i64 * self, extc_arena *__extc_home) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    int64_t ncap = (self->cap * 2);
    if (ncap < 4) {
        extc_arena_release(&__extc_a[2]);
        ncap = 4;
        extc_arena_release(&__extc_a[2]);
    }
    slice_i64 nb = (slice_i64){ .data = (int64_t *)extc_arena_alloc(&(*__extc_home), (int64_t)(ncap) * (int64_t)sizeof(int64_t), "examples/tour-plots.extc", 175), .len = (int64_t)(ncap) };
    int64_t i = 0;
    while (i < self->len) {
        extc_arena_release(&__extc_a[2]);
        (*slice_i64_index(nb, (int64_t)(i), "examples/tour-plots.extc", 178)) = (*slice_i64_index(self->buf, (int64_t)(i), "examples/tour-plots.extc", 178));
        i = (i + 1);
        extc_arena_release(&__extc_a[2]);
    }
    self->buf = nb;
    self->cap = ncap;
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static void varArray_i64_push(varArray_i64 * self, int64_t v, extc_arena *__extc_home) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    if (self->len == self->cap) {
        extc_arena_release(&__extc_a[2]);
        varArray_i64_grow(self, __extc_home);
        extc_arena_release(&__extc_a[2]);
    }
    (*slice_i64_index(self->buf, (int64_t)(self->len), "examples/tour-plots.extc", 187)) = v;
    self->len = (self->len + 1);
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static option_i64 varArray_i64_get(varArray_i64 * self, int64_t i) {
    if ((i < 0) || (i >= self->len)) {
        return (option_i64){ .tag = option_i64_none };
    }
    return (option_i64){ .tag = option_i64_some, .u.some = {._0 = (*slice_i64_index(self->buf, (int64_t)(i), "examples/tour-plots.extc", 200))} };
}

EXTC_INLINE int64_t pool$pool_Shape_pLow(int64_t e) {
    return (e & ((int64_t)(4294967295)));
}

EXTC_INLINE int64_t pool$pool_Shape_pDense(int64_t e) {
    return ((e & ((int64_t)(4294967295))) - ((int64_t)(1)));
}

EXTC_INLINE int64_t pool$pool_Shape_pGen(int64_t e) {
    return (e >> extc_shiftCount((int64_t)(((int64_t)(32))), 64, "examples/tour-plots.extc", 118));
}

EXTC_INLINE int64_t pool$pool_Shape_pPack(int64_t gen, int64_t low) {
    return ((gen << extc_shiftCount((int64_t)(((int64_t)(32))), 64, "examples/tour-plots.extc", 120)) | low);
}

EXTC_INLINE int64_t pool$pool_Shape_pEpMask(void) {
    return ((((int64_t)(1)) << extc_shiftCount((int64_t)(pool$HANDLE_EPOCH_BITS), 64, "examples/tour-plots.extc", 124)) - ((int64_t)(1)));
}

EXTC_INLINE int64_t pool$pool_Shape_pEp(int64_t v) {
    return (v & pool$pool_Shape_pEpMask());
}

EXTC_INLINE bool pool$pool_Shape_pFree(pool$pool_Shape * self, int64_t e) {
    int64_t lo = pool$pool_Shape_pLow(e);
    return ((lo == ((int64_t)(0))) || (lo > self->cap));
}

static pool$pool_Shape pool$pool_Shape_withCap(int64_t n, int64_t __extc_home_zone) {
    extc_arena __extc_a[2] = {0};
    pool$pool_Shape __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    __extc_ret_v = pool$pool_Shape_withParent(((int64_t)((-1))), n, __extc_home_zone);
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    return __extc_ret_v;
}

static pool$pool_Shape pool$pool_Shape_withParent(int64_t parent, int64_t n, int64_t __extc_home_zone) {
    extc_arena __extc_a[3] = {0};
    pool$pool_Shape __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    int64_t rp = extc_pool_new_at(parent, __extc_home_zone);
    uint64_t rpg = extc_pool_generation(rp);
    int64_t c = n;
    if (c < ((int64_t)(8))) {
        extc_arena_release(&__extc_a[2]);
        c = ((int64_t)(8));
        extc_arena_release(&__extc_a[2]);
    }
    pool$pool_Shape p = (pool$pool_Shape){.vals = (slice_Shape){ .data = (ExtcDynHandle *)extc_pool_take_raw((int64_t)(rp), (int64_t)(c) * (int64_t)sizeof(ExtcDynHandle)), .len = (int64_t)(c) }, .slots = (slice_i32){ .data = (int32_t *)extc_pool_take_raw((int64_t)(rp), (int64_t)(c) * (int64_t)sizeof(int32_t)), .len = (int64_t)(c) }, .ent = (slice_i64){ .data = (int64_t *)extc_pool_take_raw((int64_t)(rp), (int64_t)(c) * (int64_t)sizeof(int64_t)), .len = (int64_t)(c) }, .pid = rp, .pidGen = rpg, .epoch = ((int64_t)(0)), .cursor = ((int32_t)(0)), .holeHead = ((int32_t)((-1))), .n = ((int64_t)(0)), .cap = c};
    __extc_ret_v = p;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return __extc_ret_v;
}

EXTC_INLINE int64_t pool$pool_Shape_len(pool$pool_Shape * self) {
    return self->n;
}

static bool pool$pool_Shape_pLive(pool$pool_Shape * self, pool$handle h) {
    if (pool$pool_Shape_pEp(h.ep) != pool$pool_Shape_pEp(self->epoch)) {
        return false;
    }
    int64_t s = ((int64_t)(h.slot));
    if ((s < ((int64_t)(0))) || (s >= self->cap)) {
        return false;
    }
    int64_t e = (*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 190));
    if (pool$pool_Shape_pFree(self, e)) {
        return false;
    }
    return (pool$pool_Shape_pGen(e) == ((int64_t)(h.gen)));
}

static bool pool$pool_Shape_contains(pool$pool_Shape * self, pool$handle h) {
    return pool$pool_Shape_pLive(self, h);
}

static option_Shape pool$pool_Shape_get(pool$pool_Shape * self, pool$handle h) {
    if (!pool$pool_Shape_contains(self, h)) {
        return (option_Shape){ .tag = option_Shape_none };
    }
    return (option_Shape){ .tag = option_Shape_some, .u.some = {._0 = (*slice_Shape_index(self->vals, (int64_t)(pool$pool_Shape_pDense((*slice_i64_index(self->ent, (int64_t)(((int64_t)(h.slot))), "examples/tour-plots.extc", 203)))), "examples/tour-plots.extc", 203))} };
}

static pool$handle pool$pool_Shape_insert(pool$pool_Shape * self, ExtcDynHandle v) {
    extc_arena __extc_a[3] = {0};
    pool$handle __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    if (pool$pool_Shape_pStaleSelf(self)) {
        extc_arena_release(&__extc_a[2]);
        pool$pool_Shape_pPoisonSelf(self);
        extc_arena_release(&__extc_a[2]);
    }
    if ((self->holeHead < ((int32_t)(0))) && (((int64_t)(self->cursor)) >= self->cap)) {
        extc_arena_release(&__extc_a[2]);
        pool$pool_Shape_grow(self);
        extc_arena_release(&__extc_a[2]);
    }
    int64_t s = ((int64_t)(0));
    if (self->holeHead >= ((int32_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        s = ((int64_t)(self->holeHead));
        self->holeHead = ((int32_t)extc_narrowI((int64_t)(((pool$pool_Shape_pLow((*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 227))) - self->cap) - ((int64_t)(2)))), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 227));
        extc_arena_release(&__extc_a[2]);
    } else {
        extc_arena_release(&__extc_a[2]);
        s = ((int64_t)(self->cursor));
        self->cursor = (self->cursor + ((int32_t)(1)));
        extc_arena_release(&__extc_a[2]);
    }
    int64_t e = (*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 232));
    (*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 233)) = pool$pool_Shape_pPack(pool$pool_Shape_pGen(e), (self->n + ((int64_t)(1))));
    (*slice_i32_index(self->slots, (int64_t)(self->n), "examples/tour-plots.extc", 234)) = ((int32_t)extc_narrowI((int64_t)(s), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 234));
    (*slice_Shape_index(self->vals, (int64_t)(self->n), "examples/tour-plots.extc", 235)) = v;
    self->n = (self->n + ((int64_t)(1)));
    __extc_ret_v = (pool$handle){.slot = ((int32_t)extc_narrowI((int64_t)(s), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 237)), .gen = ((int32_t)extc_narrowI((int64_t)(pool$pool_Shape_pGen(e)), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 237)), .ep = pool$pool_Shape_pEp(self->epoch)};
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return __extc_ret_v;
}

static bool pool$pool_Shape_remove(pool$pool_Shape * self, pool$handle h) {
    if (!pool$pool_Shape_pLive(self, h)) {
        return false;
    }
    int64_t s = ((int64_t)(h.slot));
    int64_t e = (*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 247));
    int64_t d = pool$pool_Shape_pDense(e);
    int64_t last = (self->n - ((int64_t)(1)));
    if (d != last) {
        (*slice_Shape_index(self->vals, (int64_t)(d), "examples/tour-plots.extc", 251)) = (*slice_Shape_index(self->vals, (int64_t)(last), "examples/tour-plots.extc", 251));
        int64_t moved = ((int64_t)((*slice_i32_index(self->slots, (int64_t)(last), "examples/tour-plots.extc", 252))));
        (*slice_i32_index(self->slots, (int64_t)(d), "examples/tour-plots.extc", 253)) = ((int32_t)extc_narrowI((int64_t)(moved), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 253));
        int64_t me = (*slice_i64_index(self->ent, (int64_t)(moved), "examples/tour-plots.extc", 254));
        (*slice_i64_index(self->ent, (int64_t)(moved), "examples/tour-plots.extc", 255)) = pool$pool_Shape_pPack(pool$pool_Shape_pGen(me), (d + ((int64_t)(1))));
    }
    self->n = last;
    (*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 261)) = pool$pool_Shape_pPack((pool$pool_Shape_pGen(e) + ((int64_t)(1))), ((((int64_t)(self->holeHead)) + self->cap) + ((int64_t)(2))));
    self->holeHead = ((int32_t)extc_narrowI((int64_t)(s), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 262));
    return true;
}

static bool pool$pool_Shape_pStaleSelf(pool$pool_Shape * self) {
    if (self->pid < ((int64_t)(0))) {
        return false;
    }
    return (extc_pool_generation(self->pid) != self->pidGen);
}

static void pool$pool_Shape_pPoisonSelf(pool$pool_Shape * self) {
    extc_arena __extc_a[2] = {0};
    extc_arena_release(&__extc_a[1]);
    int64_t __extc_pn0 = (int64_t)(((int64_t)(0)));
    self->vals = (slice_Shape){ .data = (ExtcDynHandle *)extc_pool_take((int64_t)(((int64_t)((-1)))), (int64_t)(__extc_pn0) * (int64_t)sizeof(ExtcDynHandle)), .len = (int64_t)(__extc_pn0) };
    int64_t __extc_pn1 = (int64_t)(((int64_t)(0)));
    self->slots = (slice_i32){ .data = (int32_t *)extc_pool_take((int64_t)(((int64_t)((-1)))), (int64_t)(__extc_pn1) * (int64_t)sizeof(int32_t)), .len = (int64_t)(__extc_pn1) };
    int64_t __extc_pn2 = (int64_t)(((int64_t)(0)));
    self->ent = (slice_i64){ .data = (int64_t *)extc_pool_take((int64_t)(((int64_t)((-1)))), (int64_t)(__extc_pn2) * (int64_t)sizeof(int64_t)), .len = (int64_t)(__extc_pn2) };
    self->n = ((int64_t)(0));
    self->cap = ((int64_t)(0));
    self->pid = ((int64_t)((-1)));
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    return;
}

static int64_t pool$pool_Shape_bytesOf(pool$pool_Shape * self) {
    if (self->pid < ((int64_t)(0))) {
        return ((int64_t)(0));
    }
    return extc_pool_bytes(self->pid);
}



EXTC_INLINE ExtcDynHandle pool$pool_Shape_atDense(pool$pool_Shape * self, int64_t i) {
    return (*slice_Shape_index(self->vals, (int64_t)(i), "examples/tour-plots.extc", 384));
}

EXTC_INLINE pool$handle pool$pool_Shape_handleAtDense(pool$pool_Shape * self, int64_t i) {
    int64_t s = ((int64_t)((*slice_i32_index(self->slots, (int64_t)(i), "examples/tour-plots.extc", 411))));
    return (pool$handle){.slot = ((int32_t)extc_narrowI((int64_t)(s), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 412)), .gen = ((int32_t)extc_narrowI((int64_t)(pool$pool_Shape_pGen((*slice_i64_index(self->ent, (int64_t)(s), "examples/tour-plots.extc", 412)))), -2147483648LL, 2147483647LL, "examples/tour-plots.extc", 412)), .ep = pool$pool_Shape_pEp(self->epoch)};
}

static void pool$pool_Shape_grow(pool$pool_Shape * self) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    if (self->pid < ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        goto __extc_ret;
        extc_arena_release(&__extc_a[2]);
    }
    int64_t ncap = (self->cap + (int64_t)extc_divI((int64_t)(self->cap), (int64_t)(((int64_t)(2))), "examples/tour-plots.extc", 458));
    self->vals = (slice_Shape){ .data = (ExtcDynHandle *)extc_pool_resize((int64_t)(self->pid), (void *)(self->vals).data, (int64_t)(ncap) * (int64_t)sizeof(ExtcDynHandle)), .len = (int64_t)(ncap) };
    self->slots = (slice_i32){ .data = (int32_t *)extc_pool_resize((int64_t)(self->pid), (void *)(self->slots).data, (int64_t)(ncap) * (int64_t)sizeof(int32_t)), .len = (int64_t)(ncap) };
    self->ent = (slice_i64){ .data = (int64_t *)extc_pool_resize((int64_t)(self->pid), (void *)(self->ent).data, (int64_t)(ncap) * (int64_t)sizeof(int64_t)), .len = (int64_t)(ncap) };
    self->cap = ncap;
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}



















EXTC_INLINE io$ostream io$ostream_shl_i64(io$ostream * self, int64_t v) {
    io$pairsReady();
    int64_t st = io$fmtI64Fast(v);
    int64_t n = (((int64_t)(24)) - st);
    extc_cout_put(extc_slice_array_24_u8(&(io$FMT), (int64_t)(st), (int64_t)(((int64_t)(24))), "examples/tour-plots.extc", 593).data, n);
    return (io$ostream){.fd = self->fd};
}

EXTC_INLINE io$ostream io$ostream_shl_slice_u8(io$ostream * self, slice_u8 v) {
    if (v.len > ((int64_t)(0))) {
        extc_cout_put(v.data, v.len);
    }
    return (io$ostream){.fd = self->fd};
}

EXTC_INLINE io$istream io$istream_shr_mut_Ref_i64(io$istream * self, int64_t * v) {
    bool g = false;
    result_i64_io$ioError __extc_m0 = io$nextI64State(((int32_t)(0)), (slice_u8){ .data = &(io$IN_BUF.data[0]), .len = 65536 }, &(io$IN_LEN), &(io$IN_POS), &(g));
    if (__extc_m0.tag == result_i64_io$ioError_success) {
        int64_t n = __extc_m0.u.success._0;
        if (g) {
            (*(v)) = n;
        } else {
            io$IN_BAD = true;
        }
    } else if (__extc_m0.tag == result_i64_io$ioError_failure) {
        io$IN_BAD = true;
    }
    return (io$istream){.fd = self->fd};
}

static string$string string$string_new(int64_t c, int64_t __extc_home_zone) {
    extc_arena __extc_a[3] = {0};
    string$string __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    int64_t rp = extc_pool_new_at(((int64_t)((-1))), __extc_home_zone);
    uint64_t rpg = extc_pool_generation(rp);
    int64_t cc = c;
    if (cc < ((int64_t)(16))) {
        extc_arena_release(&__extc_a[2]);
        cc = ((int64_t)(16));
        extc_arena_release(&__extc_a[2]);
    }
    string$string s = (string$string){.buf = (slice_u8){ .data = (uint8_t *)extc_pool_take_raw((int64_t)(rp), (int64_t)(cc) * (int64_t)sizeof(uint8_t)), .len = (int64_t)(cc) }, .n = ((int64_t)(0)), .cap = cc, .pid = rp, .pidGen = rpg};
    __extc_ret_v = s;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return __extc_ret_v;
}

static slice_u8 string$string_toSlice(string$string * self, extc_arena *__extc_home) {
    extc_arena __extc_a[3] = {0};
    slice_u8 __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    slice_u8 out = (slice_u8){ .data = (uint8_t *)extc_arena_alloc(&(*__extc_home), (int64_t)(self->n) * (int64_t)sizeof(uint8_t), "examples/tour-plots.extc", 60), .len = (int64_t)(self->n) };
    int64_t i = 0;
    while (i < self->n) {
        extc_arena_release(&__extc_a[2]);
        (*slice_u8_index(out, (int64_t)(i), "examples/tour-plots.extc", 63)) = (*slice_u8_index(self->buf, (int64_t)(i), "examples/tour-plots.extc", 63));
        i = (i + ((int64_t)(1)));
        extc_arena_release(&__extc_a[2]);
    }
    __extc_ret_v = out;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return __extc_ret_v;
}









static void string$string_grow(string$string * self) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    if (self->pid < ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        goto __extc_ret;
        extc_arena_release(&__extc_a[2]);
    }
    int64_t ncap = (self->cap + (int64_t)extc_divI((int64_t)(self->cap), (int64_t)(((int64_t)(2))), "examples/tour-plots.extc", 320));
    self->buf = (slice_u8){ .data = (uint8_t *)extc_pool_resize_raw((int64_t)(self->pid), (void *)(self->buf).data, (int64_t)(ncap) * (int64_t)sizeof(uint8_t)), .len = (int64_t)(ncap) };
    self->cap = ncap;
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static void string$string_push(string$string * self, uint8_t b) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    if (string$string_pStale(self)) {
        extc_arena_release(&__extc_a[2]);
        string$string_pPoison(self);
        extc_arena_release(&__extc_a[2]);
    }
    if (self->n >= self->cap) {
        extc_arena_release(&__extc_a[2]);
        string$string_grow(self);
        extc_arena_release(&__extc_a[2]);
    }
    (*slice_u8_index(self->buf, (int64_t)(self->n), "examples/tour-plots.extc", 328)) = b;
    self->n = (self->n + ((int64_t)(1)));
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static void string$string_append(string$string * self, slice_u8 s) {
    extc_arena __extc_a[3] = {0};
    extc_arena_release(&__extc_a[1]);
    if (string$string_pStale(self)) {
        extc_arena_release(&__extc_a[2]);
        string$string_pPoison(self);
        extc_arena_release(&__extc_a[2]);
    }
    if (s.len <= ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        goto __extc_ret;
        extc_arena_release(&__extc_a[2]);
    }
    int64_t need = (self->n + s.len);
    while (self->cap < need) {
        extc_arena_release(&__extc_a[2]);
        string$string_grow(self);
        extc_arena_release(&__extc_a[2]);
    }
    slice_u8_copy((slice_u8)(extc_slice_slice_u8(self->buf, (int64_t)(self->n), (int64_t)(need), "examples/tour-plots.extc", 342)), (slice_u8)(s), (int64_t)(s.len), "examples/tour-plots.extc", 342);
    self->n = need;
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static bool string$string_pStale(string$string * self) {
    if (self->pid < ((int64_t)(0))) {
        return false;
    }
    return (extc_pool_generation(self->pid) != self->pidGen);
}

static void string$string_pPoison(string$string * self) {
    extc_arena __extc_a[2] = {0};
    extc_arena_release(&__extc_a[1]);
    int64_t __extc_pn0 = (int64_t)(((int64_t)(0)));
    self->buf = (slice_u8){ .data = (uint8_t *)extc_pool_take((int64_t)(((int64_t)((-1)))), (int64_t)(__extc_pn0) * (int64_t)sizeof(uint8_t)), .len = (int64_t)(__extc_pn0) };
    self->n = ((int64_t)(0));
    self->cap = ((int64_t)(0));
    self->pid = ((int64_t)((-1)));
    extc_arena_release(&__extc_a[1]);
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    return;
}

static int64_t rect_area(rect * self) {
    return (self->w * self->h);
}

static int64_t circle_area(circle * self) {
    return ((((int64_t)(3)) * self->r) * self->r);
}

static int64_t tri_area(tri * self) {
    return (int64_t)extc_divI((int64_t)((self->b * self->h)), (int64_t)(((int64_t)(2))), "examples/tour-plots.extc", 27);
}

EXTC_INLINE result_i64_io$ioError io$fillState(int32_t fd, slice_u8 buf, int64_t * len, int64_t * pos) {
    int64_t n = read(fd, buf.data, buf.len);
    if (n < ((int64_t)(0))) {
        return (result_i64_io$ioError){ .tag = result_i64_io$ioError_failure, .u.failure = {._0 = (io$ioError){ .tag = io$ioError_readFailed, .u.readFailed = {._0 = fd} }} };
    }
    (*(len)) = n;
    (*(pos)) = 0;
    return (result_i64_io$ioError){ .tag = result_i64_io$ioError_success, .u.success = {._0 = n} };
}

EXTC_INLINE bool io$accDigit(int64_t * v, int64_t * nd, int64_t d) {
    if ((*(nd)) < ((int64_t)(18))) {
        (*(v)) = (((*(v)) * ((int64_t)(10))) + d);
    } else {
        if ((*(v)) > (int64_t)extc_divI((int64_t)((io$I64_MAX - d)), (int64_t)(((int64_t)(10))), "examples/tour-plots.extc", 223)) {
            return false;
        }
        (*(v)) = (((*(v)) * ((int64_t)(10))) + d);
    }
    (*(nd)) = ((*(nd)) + ((int64_t)(1)));
    return true;
}

EXTC_INLINE result_i64_io$ioError io$nextI64State(int32_t fd, slice_u8 buf, int64_t * len, int64_t * pos, bool * got) {
    bool neg = false;
    int64_t v = 0;
    int64_t nd = 0;
    bool saw = false;
    bool seen = false;
    int64_t pushed = ((int64_t)(0));
    bool bad = false;
    int64_t b = ((int64_t)(0));
    while (true) {
        if (pushed == ((int64_t)((-2)))) {
            pushed = ((int64_t)(0));
            b = ((int64_t)((-1)));
        } else {
            if (pushed > ((int64_t)(0))) {
                b = pushed;
                pushed = ((int64_t)(0));
            } else {
                if ((*(pos)) >= (*(len))) {
                    result_i64_io$ioError __extc_try0 = io$fillState(fd, buf, len, pos);
                    if (__extc_try0.tag != result_i64_io$ioError_success) {
                        return (result_i64_io$ioError){ .tag = result_i64_io$ioError_failure, .u.failure = { ._0 = __extc_try0.u.failure._0 } };
                    }
                    int64_t n = __extc_try0.u.success._0;
                    if (n == ((int64_t)(0))) {
                        b = ((int64_t)((-1)));
                    } else {
                        b = ((int64_t)((*slice_u8_index(buf, (int64_t)((*(pos))), "examples/tour-plots.extc", 250))));
                        (*(pos)) = ((*(pos)) + ((int64_t)(1)));
                    }
                } else {
                    b = ((int64_t)((*slice_u8_index(buf, (int64_t)((*(pos))), "examples/tour-plots.extc", 254))));
                    (*(pos)) = ((*(pos)) + ((int64_t)(1)));
                }
            }
        }
        if (!seen) {
            if (b < ((int64_t)(0))) {
                break;
            }
            if (!io$isSpaceByte(b)) {
                seen = true;
                if (b == ((int64_t)(45))) {
                    neg = true;
                } else {
                    pushed = b;
                }
            }
            continue;
        }
        if (bad) {
            if (b < ((int64_t)(0))) {
                pushed = ((int64_t)((-2)));
            } else {
                (*(pos)) = ((*(pos)) - ((int64_t)(1)));
            }
            break;
        }
        if (b < ((int64_t)(0))) {
            break;
        }
        if ((b >= ((int64_t)(48))) && (b <= ((int64_t)(57)))) {
            saw = true;
            if (!io$accDigit(&(v), &(nd), (b - ((int64_t)(48))))) {
                return (result_i64_io$ioError){ .tag = result_i64_io$ioError_failure, .u.failure = {._0 = (io$ioError){ .tag = io$ioError_lineTooLong, .u.lineTooLong = {._0 = v} }} };
            }
            while ((*(pos)) < (*(len))) {
                int64_t nb = ((int64_t)((*slice_u8_index(buf, (int64_t)((*(pos))), "examples/tour-plots.extc", 283))));
                if ((nb < ((int64_t)(48))) || (nb > ((int64_t)(57)))) {
                    break;
                }
                (*(pos)) = ((*(pos)) + ((int64_t)(1)));
                if (!io$accDigit(&(v), &(nd), (nb - ((int64_t)(48))))) {
                    return (result_i64_io$ioError){ .tag = result_i64_io$ioError_failure, .u.failure = {._0 = (io$ioError){ .tag = io$ioError_lineTooLong, .u.lineTooLong = {._0 = v} }} };
                }
            }
            continue;
        }
        if (!saw) {
            continue;
        }
        if (b == ((int64_t)(10))) {
            break;
        }
        if (b == ((int64_t)(13))) {
            if ((*(pos)) < (*(len))) {
                if (((int64_t)((*slice_u8_index(buf, (int64_t)((*(pos))), "examples/tour-plots.extc", 295)))) == ((int64_t)(10))) {
                    (*(pos)) = ((*(pos)) + ((int64_t)(1)));
                }
            }
            break;
        }
        bad = true;
    }
    (*(got)) = saw;
    if (!saw) {
        return (result_i64_io$ioError){ .tag = result_i64_io$ioError_success, .u.success = {._0 = ((int64_t)(0))} };
    }
    if (neg) {
        return (result_i64_io$ioError){ .tag = result_i64_io$ioError_success, .u.success = {._0 = (((int64_t)(0)) - v)} };
    }
    return (result_i64_io$ioError){ .tag = result_i64_io$ioError_success, .u.success = {._0 = v} };
}

EXTC_INLINE bool io$isSpaceByte(int64_t b) {
    if (b == ((int64_t)(32))) {
        return true;
    }
    if (b == ((int64_t)(9))) {
        return true;
    }
    if (b == ((int64_t)(10))) {
        return true;
    }
    if (b == ((int64_t)(13))) {
        return true;
    }
    if (b == ((int64_t)(11))) {
        return true;
    }
    if (b == ((int64_t)(12))) {
        return true;
    }
    return false;
}





EXTC_INLINE void io$pairsReady(void) {
    if (io$PAIRS_READY) {
        return;
    }
    int64_t i = 0;
    while (i < ((int64_t)(200))) {
        io$PAIRS.data[extc_checkedIndex((int64_t)(i), 200, "examples/tour-plots.extc", 755)] = (*slice_u8_index(io$DIGITS, (int64_t)(i), "examples/tour-plots.extc", 755));
        i = (i + 1);
    }
    io$PAIRS_READY = true;
}

EXTC_INLINE int64_t io$fmtI64Fast(int64_t v) {
    int64_t end = ((int64_t)(24));
    int64_t u = v;
    bool neg = (v < ((int64_t)(0)));
    if (neg) {
        u = (((int64_t)(0)) - u);
    }
    while (u >= ((int64_t)(100))) {
        int64_t r = (int64_t)extc_modI((int64_t)(u), (int64_t)(((int64_t)(100))), "examples/tour-plots.extc", 773);
        u = (int64_t)extc_divI((int64_t)(u), (int64_t)(((int64_t)(100))), "examples/tour-plots.extc", 774);
        end = (end - ((int64_t)(2)));
        io$FMT.data[extc_checkedIndex((int64_t)(end), 24, "examples/tour-plots.extc", 776)] = io$PAIRS.data[extc_checkedIndex((int64_t)((r * ((int64_t)(2)))), 200, "examples/tour-plots.extc", 776)];
        io$FMT.data[extc_checkedIndex((int64_t)((end + 1)), 24, "examples/tour-plots.extc", 777)] = io$PAIRS.data[extc_checkedIndex((int64_t)(((r * ((int64_t)(2))) + ((int64_t)(1)))), 200, "examples/tour-plots.extc", 777)];
    }
    if (u >= ((int64_t)(10))) {
        end = (end - ((int64_t)(2)));
        io$FMT.data[extc_checkedIndex((int64_t)(end), 24, "examples/tour-plots.extc", 781)] = io$PAIRS.data[extc_checkedIndex((int64_t)((u * ((int64_t)(2)))), 200, "examples/tour-plots.extc", 781)];
        io$FMT.data[extc_checkedIndex((int64_t)((end + 1)), 24, "examples/tour-plots.extc", 782)] = io$PAIRS.data[extc_checkedIndex((int64_t)(((u * ((int64_t)(2))) + ((int64_t)(1)))), 200, "examples/tour-plots.extc", 782)];
    } else {
        end = (end - ((int64_t)(1)));
        io$FMT.data[extc_checkedIndex((int64_t)(end), 24, "examples/tour-plots.extc", 785)] = ((uint8_t)extc_narrowU((uint64_t)((48 + u)), 255ULL, "examples/tour-plots.extc", 785));
    }
    if (neg) {
        end = (end - ((int64_t)(1)));
        io$FMT.data[extc_checkedIndex((int64_t)(end), 24, "examples/tour-plots.extc", 789)] = ((uint8_t)extc_narrowU((uint64_t)(45), 255ULL, "examples/tour-plots.extc", 789));
    }
    return end;
}





static string$string string$withCap(int64_t c, int64_t __extc_home_zone) {
    extc_arena __extc_a[2] = {0};
    string$string __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    __extc_ret_v = string$string_new(c, __extc_home_zone);
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    return __extc_ret_v;
}

static int64_t minArea(void) {
    return ((int64_t)(10));
}

static void pushI64(string$string * s, int64_t v) {
    extc_arena __extc_a[3] = {0};
    extc_rec_enter("examples/tour-plots.extc", 32);
    extc_arena_release(&__extc_a[1]);
    int64_t n = v;
    if (n < ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        string$string_append(s, (slice_u8){ .data = (uint8_t *)"-", .len = sizeof("-") - 1 });
        n = (((int64_t)(0)) - n);
        extc_arena_release(&__extc_a[2]);
    }
    if (n >= ((int64_t)(10))) {
        extc_arena_release(&__extc_a[2]);
        pushI64(s, (int64_t)extc_divI((int64_t)(n), (int64_t)(((int64_t)(10))), "examples/tour-plots.extc", 35));
        extc_arena_release(&__extc_a[2]);
    }
    string$string_push(s, ((uint8_t)extc_narrowU((uint64_t)((((int64_t)(48)) + (int64_t)extc_modI((int64_t)(n), (int64_t)(((int64_t)(10))), "examples/tour-plots.extc", 36))), 255ULL, "examples/tour-plots.extc", 36)));
    extc_arena_release(&__extc_a[1]);
    --__extc_rec_depth;
    goto __extc_ret;
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    return;
}

static slice_u8 kindName(int64_t kind) {
    if (kind == ((int64_t)(1))) {
        return (slice_u8){ .data = (uint8_t *)"rect  ", .len = sizeof("rect  ") - 1 };
    }
    if (kind == ((int64_t)(2))) {
        return (slice_u8){ .data = (uint8_t *)"circle", .len = sizeof("circle") - 1 };
    }
    return (slice_u8){ .data = (uint8_t *)"tri   ", .len = sizeof("tri   ") - 1 };
}

static string$string line(int64_t idx, int64_t kind, int64_t area, int64_t __extc_home_zone) {
    extc_arena __extc_a[2] = {0};
    int64_t __extc_zm1 = extc_pool_zoneEnter();   /* 函数体是一个地方 */
    string$string __extc_ret_v;
    extc_arena_release(&__extc_a[1]);
    string$string out = string$withCap(((int64_t)(48)), __extc_home_zone);
    string$string_append(&(out), kindName(kind));
    string$string_append(&(out), (slice_u8){ .data = (uint8_t *)" #", .len = sizeof(" #") - 1 });
    pushI64(&(out), idx);
    string$string_append(&(out), (slice_u8){ .data = (uint8_t *)"  area=", .len = sizeof("  area=") - 1 });
    pushI64(&(out), area);
    __extc_ret_v = out;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_pool_zoneLeaveTo(__extc_zm1);
    return __extc_ret_v;
}

int main(void) {
    extc_arena __extc_a[5] = {0};
    int64_t __extc_zm1 = extc_pool_zoneEnter();   /* 函数体是一个地方 */
    int32_t __extc_ret_v;
    extc_arena *__extc_home = &__extc_a[1];   /* main's home arena is its own body */
    atexit(extc_cout_flush);
    extc_arena_release(&__extc_a[1]);
    int64_t n = ((int64_t)(0));
    io$istream_shr_mut_Ref_i64(&(io$cin), &(n));
    if (n <= ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"no plots\n", .len = sizeof("no plots\n") - 1 });
        extc_cout_flush();
        __extc_ret_v = 0;
        goto __extc_ret;
        extc_arena_release(&__extc_a[2]);
    }
    varArray_i64 kinds = varArray_i64_withCap((n + ((int64_t)(1))), __extc_home);
    pool$pool_Shape plots = pool$pool_Shape_withCap((n + ((int64_t)(1))), __extc_zm1);
    int64_t i = ((int64_t)(0));
    while (i < n) {
        extc_arena_release(&__extc_a[2]);
        int64_t kind = ((int64_t)(0));
        int64_t a = ((int64_t)(0));
        int64_t b = ((int64_t)(0));
        io$istream_shr_mut_Ref_i64((io$istream[]){ io$istream_shr_mut_Ref_i64((io$istream[]){ io$istream_shr_mut_Ref_i64(&(io$cin), &(kind)) }, &(a)) }, &(b));
        if (kind == ((int64_t)(1))) {
            extc_arena_release(&__extc_a[3]);
            rect __extc_dyp0 = (rect){.w = a, .h = b};
            pool$pool_Shape_insert(&(plots), extc_dyn_put((const void *)&__extc_dyp0, (int64_t)sizeof(rect), &extc_vt$Shape$rect));
            extc_arena_release(&__extc_a[3]);
        } else {
            if (kind == ((int64_t)(2))) {
                extc_arena_release(&__extc_a[3]);
                circle __extc_dyp1 = (circle){.r = a};
                pool$pool_Shape_insert(&(plots), extc_dyn_put((const void *)&__extc_dyp1, (int64_t)sizeof(circle), &extc_vt$Shape$circle));
                extc_arena_release(&__extc_a[3]);
            } else {
                extc_arena_release(&__extc_a[3]);
                tri __extc_dyp2 = (tri){.b = a, .h = b};
                pool$pool_Shape_insert(&(plots), extc_dyn_put((const void *)&__extc_dyp2, (int64_t)sizeof(tri), &extc_vt$Shape$tri));
                extc_arena_release(&__extc_a[3]);
            }
        }
        varArray_i64_push(&(kinds), kind, __extc_home);
        i = (i + ((int64_t)(1)));
        extc_arena_release(&__extc_a[2]);
    }
    io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"kind   #  area\n", .len = sizeof("kind   #  area\n") - 1 });
    io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"--------------\n", .len = sizeof("--------------\n") - 1 });
    int64_t total = ((int64_t)(0));
    int64_t best = ((int64_t)(0));
    int64_t bestAt = ((int64_t)(0));
    i = ((int64_t)(0));
    while (i < pool$pool_Shape_len(&(plots))) {
        extc_arena_release(&__extc_a[2]);
        int64_t __extc_zm2 = extc_pool_zoneEnter();
        ExtcDynSlot *__extc_ds3 = extc_dyn_slot(pool$pool_Shape_atDense(&(plots), i), "examples/tour-plots.extc", 94);
        int64_t area = ((const struct extc_vt$Shape_t *)__extc_ds3->vt)->area(__extc_ds3->addr);
        io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), string$string_toSlice((string$string[]){ line(i, (varArray_i64_get(&(kinds), i)).u.some._0, area, __extc_zm2) }, __extc_home)) }, (slice_u8){ .data = (uint8_t *)"\n", .len = sizeof("\n") - 1 });
        total = (total + area);
        if (area > best) {
            extc_arena_release(&__extc_a[3]);
            best = area;
            bestAt = i;
            extc_arena_release(&__extc_a[3]);
        }
        i = (i + ((int64_t)(1)));
        extc_pool_zoneLeaveTo(__extc_zm2);
        extc_arena_release(&__extc_a[2]);
    }
    io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"--------------\n", .len = sizeof("--------------\n") - 1 });
    io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"plots=", .len = sizeof("plots=") - 1 }) }, pool$pool_Shape_len(&(plots))) }, (slice_u8){ .data = (uint8_t *)" total=", .len = sizeof(" total=") - 1 }) }, total);
    io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)" max=", .len = sizeof(" max=") - 1 }) }, best) }, (slice_u8){ .data = (uint8_t *)" (at #", .len = sizeof(" (at #") - 1 }) }, bestAt) }, (slice_u8){ .data = (uint8_t *)")\n", .len = sizeof(")\n") - 1 });
    int64_t removed = ((int64_t)(0));
    pool$handle stale = pool$pool_Shape_handleAtDense(&(plots), ((int64_t)(0)));
    int64_t staleArea = ((int64_t)(0));
    i = pool$pool_Shape_len(&(plots));
    while (i > ((int64_t)(0))) {
        extc_arena_release(&__extc_a[2]);
        i = (i - ((int64_t)(1)));
        ExtcDynSlot *__extc_ds4 = extc_dyn_slot(pool$pool_Shape_atDense(&(plots), i), "examples/tour-plots.extc", 112);
        int64_t area__2 = ((const struct extc_vt$Shape_t *)__extc_ds4->vt)->area(__extc_ds4->addr);
        if (area__2 < minArea()) {
            extc_arena_release(&__extc_a[3]);
            pool$handle h = pool$pool_Shape_handleAtDense(&(plots), i);
            if (pool$pool_Shape_remove(&(plots), h)) {
                extc_arena_release(&__extc_a[4]);
                stale = h;
                staleArea = area__2;
                removed = (removed + ((int64_t)(1)));
                extc_arena_release(&__extc_a[4]);
            }
            extc_arena_release(&__extc_a[3]);
        }
        extc_arena_release(&__extc_a[2]);
    }
    io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"removed=", .len = sizeof("removed=") - 1 }) }, removed) }, (slice_u8){ .data = (uint8_t *)" live=", .len = sizeof(" live=") - 1 }) }, pool$pool_Shape_len(&(plots))) }, (slice_u8){ .data = (uint8_t *)" freed_bytes=", .len = sizeof(" freed_bytes=") - 1 }) }, pool$pool_Shape_bytesOf(&(plots))) }, (slice_u8){ .data = (uint8_t *)"\n", .len = sizeof("\n") - 1 });
    option_Shape __extc_m5 = pool$pool_Shape_get(&(plots), stale);
    if (__extc_m5.tag == option_Shape_some) {
        ExtcDynHandle v = __extc_m5.u.some._0;
        extc_arena_release(&__extc_a[2]);
        ExtcDynSlot *__extc_ds6 = extc_dyn_slot(v, "examples/tour-plots.extc", 126);
        io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"陈旧句柄竟读到 ", .len = sizeof("陈旧句柄竟读到 ") - 1 }) }, ((const struct extc_vt$Shape_t *)__extc_ds6->vt)->area(__extc_ds6->addr)) }, (slice_u8){ .data = (uint8_t *)"（不该发生）\n", .len = sizeof("（不该发生）\n") - 1 });
        extc_arena_release(&__extc_a[2]);
    } else if (__extc_m5.tag == option_Shape_none) {
        extc_arena_release(&__extc_a[2]);
        io$ostream_shl_slice_u8((io$ostream[]){ io$ostream_shl_i64((io$ostream[]){ io$ostream_shl_slice_u8(&(io$cout), (slice_u8){ .data = (uint8_t *)"陈旧句柄(area=", .len = sizeof("陈旧句柄(area=") - 1 }) }, staleArea) }, (slice_u8){ .data = (uint8_t *)") → none：池的世代挡住了它\n", .len = sizeof(") → none：池的世代挡住了它\n") - 1 });
        extc_arena_release(&__extc_a[2]);
    }
    extc_cout_flush();
    __extc_ret_v = 0;
    goto __extc_ret;
    extc_arena_release(&__extc_a[1]);
__extc_ret:
    extc_arena_destroy(&__extc_a[1]);
    extc_arena_destroy(&__extc_a[2]);
    extc_arena_destroy(&__extc_a[3]);
    extc_arena_destroy(&__extc_a[4]);
    extc_pool_zoneLeaveTo(__extc_zm1);
    extc_cout_flush();
    return (int)__extc_ret_v;
}

static int64_t extc_th$Shape$rect$area(void *self) { return rect_area((rect *)self); }
static const struct extc_vt$Shape_t __attribute__((unused)) extc_vt$Shape$rect = { extc_th$Shape$rect$area };
static int64_t extc_th$Shape$circle$area(void *self) { return circle_area((circle *)self); }
static const struct extc_vt$Shape_t __attribute__((unused)) extc_vt$Shape$circle = { extc_th$Shape$circle$area };
static int64_t extc_th$Shape$tri$area(void *self) { return tri_area((tri *)self); }
static const struct extc_vt$Shape_t __attribute__((unused)) extc_vt$Shape$tri = { extc_th$Shape$tri$area };
