#!/usr/bin/env python3
"""Generate stdlib/INDEX: which module declares which `impl` method.

Why: an `impl` block is only visible when its module is imported (semantic import), so the
error "no method `parseJSON` on `string`" usually means "you did not import the module that
declares it". Answering that at the error site by *loading* candidate modules would undo the
isolation that makes imports semantic, so the answer is precomputed here, committed, and read
by the compiler on a miss only.

    tools/gen_index.py          rewrite stdlib/INDEX
    tools/gen_index.py --check  exit 1 when stdlib/INDEX is stale (check.sh runs this)
"""
import re, sys, glob, os

def modules():
    out = []
    for path in sorted(glob.glob('stdlib/**/*.extc', recursive=True)):
        rel = os.path.relpath(path, 'stdlib')[:-5].replace(os.sep, '::')
        src = open(path, encoding='utf-8').read()
        src = re.sub(r'/\*.*?\*/', lambda m: re.sub(r'[^\n]', ' ', m.group(0)), src, flags=re.S)
        for m in re.finditer(r'^impl\s+([\w:]+)\s*\{', src, re.M):
            ty, i, depth = m.group(1), m.end(), 1
            while i < len(src) and depth:
                if src[i] == '{': depth += 1
                elif src[i] == '}': depth -= 1
                i += 1
            body = src[m.end():i-1]
            for mm in re.finditer(r'\bfn\s+(\w+)\s*\(', body):
                out.append((mm.group(1), ty, rel))
    return out

rows = sorted(set(modules()))
text = ("# Generated by tools/gen_index.py -- do not edit by hand.\n"
        "# method<TAB>type<TAB>declaring module. check.sh fails when this file is stale.\n"
        + ''.join(f'{m}\t{t}\t{mod}\n' for m, t, mod in rows))
if '--check' in sys.argv:
    cur = open('stdlib/INDEX', encoding='utf-8').read() if os.path.exists('stdlib/INDEX') else ''
    if cur != text:
        print('stdlib/INDEX is stale -- run tools/gen_index.py'); sys.exit(1)
    print(f'ok  stdlib/INDEX 与源码一致（{len(rows)} 条 impl 方法）'); sys.exit(0)
open('stdlib/INDEX', 'w', encoding='utf-8').write(text)
print(f'stdlib/INDEX 已写：{len(rows)} 条')
