#!/usr/bin/env python3
"""Generate stdlib/INDEX: which module declares which `impl` method.

Why: an `impl` block is only visible when its module is imported (semantic import), so the
error "no method `parseJSON` on `string`" usually means "you did not import the module that
declares it". Answering that at the error site by *loading* candidate modules would undo the
isolation that makes imports semantic, so the answer is precomputed here, committed, and read
by the compiler on a miss only.

    tools/gen_index.py          rewrite stdlib/INDEX
    tools/gen_index.py --check  exit 1 when stdlib/INDEX is stale (check.sh runs this)
"""
import re, sys, glob, os

def modules():
    out = []
    for path in sorted(glob.glob('stdlib/**/*.extc', recursive=True)):
        rel = os.path.relpath(path, 'stdlib')[:-5].replace(os.sep, '::')
        src = open(path, encoding='utf-8').read()
        src = re.sub(r'/\*.*?\*/', lambda m: re.sub(r'[^\n]', ' ', m.group(0)), src, flags=re.S)
        for m in re.finditer(r'^impl\s+([\w:]+)\s*\{', src, re.M):
            ty, i, depth = m.group(1), m.end(), 1
            while i < len(src) and depth:
                if src[i] == '{': depth += 1
                elif src[i] == '}': depth -= 1
                i += 1
            body = src[m.end():i-1]
            # `@private` may precede a member, and it is part of the member's meaning, so it
            # travels into the index (the manual's coverage list keeps only `public` ones).
            for mm in re.finditer(r'((?:@private\s+)?)\bfn\s+(\w+)\s*\(', body):
                out.append((mm.group(2), ty, rel,
                            'private' if mm.group(1).strip() else 'public', 'method'))
            # A field is `name: type` at the **start of a line**; the `(?!:)` keeps `mod::NAME`
            # (a qualified reference such as `io::IN_BAD`) out of the list.
            for fm in re.finditer(r'^\s*(@private\s+)?([a-z]\w*)\s*:\s*(?!:)', body, re.M):
                out.append((fm.group(2), ty, rel,
                            'private' if fm.group(1) else 'public', 'field'))
    return out

rows = sorted(set(modules()))
text = ("# Generated by tools/gen_index.py -- do not edit by hand.\n"
        "# name<TAB>type<TAB>module<TAB>visibility<TAB>kind; check.sh fails when this file is stale.\n"
        "# The compiler reads only the first three columns (a `no method` diagnostic names the\n"
        "# module to import); tools/manual-surface.txt is derived from all five.\n"
        + ''.join(f'{m}\t{t}\t{mod}\t{vis}\t{kind}\n' for m, t, mod, vis, kind in rows))
if '--check' in sys.argv:
    cur = open('stdlib/INDEX', encoding='utf-8').read() if os.path.exists('stdlib/INDEX') else ''
    if cur != text:
        print('stdlib/INDEX is stale -- run tools/gen_index.py'); sys.exit(1)
    pub = sum(1 for r in rows if r[3] == 'public')
    print(f'ok  stdlib/INDEX 与源码一致（{len(rows)} 条成员：公开 {pub} · 私有 {len(rows)-pub}）'); sys.exit(0)
open('stdlib/INDEX', 'w', encoding='utf-8').write(text)
print(f'stdlib/INDEX 已写：{len(rows)} 条')
