#!/usr/bin/env python3
"""列出标准库的**公开面**：应当被手册逐项覆盖的成员。

来源是每个模块的 `struct` 体与 `impl` 块：成员缺省公开，`@private` 才是内部。
输出 `tools/manual-surface.txt`（`模块<TAB>类型<TAB>成员<TAB>种类`），按模块排序。

    tools/manual_surface.py           重新生成
    tools/manual_surface.py --check   与清单不一致则失败（check.sh 调用）
"""
import re, sys, glob, os

def members(path, rel):
    src = open(path, encoding='utf-8').read()
    src = re.sub(r'/\*.*?\*/', lambda m: re.sub(r'[^\n]', ' ', m.group(0)), src, flags=re.S)
    src = re.sub(r'//[^\n]*', lambda m: ' ' * (m.end() - m.start()), src)
    out = []
    # struct 体：字段与方法
    for m in re.finditer(r'^struct\s+(\w+)', src, re.M):
        ty, i, depth = m.group(1), src.index('{', m.end()), 1
        while i < len(src) and depth:
            if src[i] == '{': depth += 1
            elif src[i] == '}': depth -= 1
            i += 1
        body = src[src.index('{', m.end())+1:i-1]
        for fm in re.finditer(r'^\s*(@private\s+)?([a-z]\w*)\s*:\s*(?!:)', body, re.M):
            if fm.group(1): continue
            out.append((ty, fm.group(2), 'field'))
        for mm in re.finditer(r'^\s*(@private\s+)?fn\s+(\w+)\s*\(', body, re.M):
            if mm.group(1): continue
            out.append((ty, mm.group(2), 'method'))
    # impl 块：只可能是方法
    for m in re.finditer(r'^(?:@private\s+)?impl\s+([\w:]+)\s*\{', src, re.M):
        ty, i, depth = m.group(1), src.index('{', m.end()), 1
        while i < len(src) and depth:
            if src[i] == '{': depth += 1
            elif src[i] == '}': depth -= 1
            i += 1
        body = src[src.index('{', m.end())+1:i-1]
        for mm in re.finditer(r'^\s*(@private\s+)?fn\s+(\w+)\s*\(', body, re.M):
            if mm.group(1): continue
            out.append((ty, mm.group(2), 'method'))
    return [(rel, t, n, k) for t, n, k in out]

rows = []
for f in sorted(glob.glob('stdlib/**/*.extc', recursive=True)):
    rows += members(f, os.path.relpath(f, 'stdlib')[:-5].replace(os.sep, '::'))
rows.sort()
text = ('# Generated by tools/manual_surface.py -- do not edit by hand.\n'
        '# 标准库的公开面：这些成员应当被 docs/manual/ 逐项覆盖。\n'
        '# module<TAB>type<TAB>member<TAB>kind\n'
        + ''.join('%s\t%s\t%s\t%s\n' % r for r in rows))
if '--check' in sys.argv:
    cur = open('tools/manual-surface.txt', encoding='utf-8').read() if os.path.exists('tools/manual-surface.txt') else ''
    if cur != text:
        print('tools/manual-surface.txt 与源码不一致 -- 跑 tools/manual_surface.py'); sys.exit(1)
    print('ok  公开面清单与源码一致（%d 个公开成员）' % len(rows)); sys.exit(0)
open('tools/manual-surface.txt', 'w', encoding='utf-8').write(text)
bymod = {}
for rel, t, n, k in rows: bymod[rel] = bymod.get(rel, 0) + 1
print('公开成员共 %d 个，分布：' % len(rows))
for rel, c in sorted(bymod.items(), key=lambda kv: -kv[1]): print('  %-16s %3d' % (rel, c))
