#!/usr/bin/env python3
"""列出标准库的**公开面**：应当被手册逐项覆盖的成员。

来源是每个模块的 `struct` 体与 `impl` 块：成员缺省公开，`@private` 才是内部。
输出 `tools/manual-surface.txt`（`模块<TAB>类型<TAB>成员<TAB>种类`），按模块排序。

    tools/manual_surface.py           重新生成
    tools/manual_surface.py --check   与清单不一致则失败（check.sh 调用）
"""
import re, sys, glob, os

# 内部成员的**文档约定**（不是强制）：编译器不阻止任何访问，手册也不对它们承诺兼容性。
# `p*` 是容器内部助手的既有命名约定；其余是逐一核对过的内部齿轮（簿记、链、槽位打包一类）。
INTERNAL_PREFIX = re.compile(r'^p[A-Z]')
# 容器的**存储字段**同样按约定属于内部：可达（编译器不阻止），但手册不把它们当 API 讲，
# 而是列入透明清单。注意 `slice` / `varArray` 的 `len` / `data` 是使用者日常要读的，保持公开。
# 判据：**簿记与机械**属内部（树的读写器 `setKey`/`setVal`/`setKid`/`setNext`、节点池 `newNode`/`freeNode`/
# `nodeCount`、表/槽位寻址 `*AtDense`/`liveAt`/`deadOf`/`handleAtDense`、打包与计数 `ep`/`gen`/`kn`/`vn`/`nx`/
# `nk`/`cnt`/`capOf`/`bytesOf`、控制台格式化 `fmtI64*`/`flushCout`/`errWrite`、终端状态字段 `rawbuf`/`saved` 等）；
# **语义操作**属公开（增删查 `insert`/`remove`/`get`、读一行 `nextLine`/`nextLineRaw`、控制台状态
# `inSync`/`inSave`/`inBad`、raw 模式开关 `on`/`raw`/`restore`、随机数 `seeded`/`nextBounded`/`shuffleI32` 等）。
INTERNAL_MACHINERY = set("""
kn vn nx nk cnt cntOf setCnt setKey setVal setKid setNext setN newNode freeNode dropChild
nodeCount nodes growStores ncap firstKey lastKey leaf leafFor lowerIn mergeLeft mergeRight
side subMinKey height kidsCnt bucketOfDense keyAtDense valAtDense dead deadOf
denseLen liveAt pidOf tagCensus ep gen gather handleAtDense chunk got fillState isSpaceByte
newlineAfter nextI64State pairsReady errWrite flushCout fmtI64 fmtI64Fast rawbuf saved inc""".split())
INTERNAL_NAMES = {'bn', 'childSlot', 'atDense', 'borrowLeft', 'borrowRight', 'accDigit',
                  'kd', 'leafOf', 'nth',
                  'buf', 'small', 'big',   # `string` 的两态存储：small = 内联缓冲，big = 升级后的池块
                  'pid', 'pidGen', 'vals', 'slots', 'ent', 'cursor', 'holeHead', 'epoch',
                  'nnodes', 'root', 'kids', 'keys', 'tags', 'n', 'cap', 'freeHead'}

def visibility(name):
    if INTERNAL_PREFIX.match(name) or name in INTERNAL_NAMES or name in INTERNAL_MACHINERY:
        return 'internal'
    return 'public'

def members(path, rel):
    src = open(path, encoding='utf-8').read()
    src = re.sub(r'/\*.*?\*/', lambda m: re.sub(r'[^\n]', ' ', m.group(0)), src, flags=re.S)
    src = re.sub(r'//[^\n]*', lambda m: ' ' * (m.end() - m.start()), src)
    out = []
    # struct 体：字段与方法
    for m in re.finditer(r'^struct\s+(\w+)', src, re.M):
        ty, i, depth = m.group(1), src.index('{', m.end()), 1
        while i < len(src) and depth:
            if src[i] == '{': depth += 1
            elif src[i] == '}': depth -= 1
            i += 1
        body = src[src.index('{', m.end())+1:i-1]
        for fm in re.finditer(r'^\s*(@private\s+)?([a-z]\w*)\s*:\s*(?!:)', body, re.M):
            if fm.group(1): continue
            out.append((ty, fm.group(2), 'field'))
        for mm in re.finditer(r'^\s*(@private\s+)?fn\s+(\w+)\s*\(', body, re.M):
            if mm.group(1): continue
            out.append((ty, mm.group(2), 'method'))
    # impl 块：只可能是方法
    for m in re.finditer(r'^(?:@private\s+)?impl\s+([\w:]+)\s*\{', src, re.M):
        ty, i, depth = m.group(1), src.index('{', m.end()), 1
        while i < len(src) and depth:
            if src[i] == '{': depth += 1
            elif src[i] == '}': depth -= 1
            i += 1
        body = src[src.index('{', m.end())+1:i-1]
        for mm in re.finditer(r'^\s*(@private\s+)?fn\s+(\w+)\s*\(', body, re.M):
            if mm.group(1): continue
            out.append((ty, mm.group(2), 'method'))
    # 顶层**自由函数**：同样是可供使用者调用的公开面（`sort<T>`、`copyInto<T>` 一类）。
    # 约定：结构体体与 impl 块内的成员缩进书写，因此列首的 `fn` 即顶层声明。
    for fm in re.finditer(r'(?m)^fn\s+(\w+)\s*\(', src):
        out.append(('-', fm.group(1), 'fn'))
    return [(rel, t, n, k, visibility(n)) for t, n, k in out]

rows = []
for f in sorted(glob.glob('stdlib/**/*.extc', recursive=True)):
    rows += members(f, os.path.relpath(f, 'stdlib')[:-5].replace(os.sep, '::'))
rows.sort()
text = ('# Generated by tools/manual_surface.py -- do not edit by hand.\n'
        '# 标准库成员按**文档约定**分类（非强制）：public 应被手册覆盖，internal 列入透明清单。\n'
        '# module<TAB>type<TAB>member<TAB>kind<TAB>visibility\n'
        + ''.join('%s\t%s\t%s\t%s\t%s\n' % r for r in rows))

def internals_page():
    by = {}
    for mod, ty, name, kind, vis in rows:
        if vis != 'internal': continue
        by.setdefault(mod, []).append((ty, name, kind))
    out = ['# 内部成员一览（透明清单）', '',
           '标准库成员**缺省公开**，编译器不阻止任何访问。本页列出**按约定属于内部**的成员：它们可达，',
           '但不受兼容性承诺保护，重构时不预告。是否使用、如何承担风险，由使用者自行判断 ——',
           '本手册的职责是把它们**列清楚**，而不是把它们锁起来。', '',
           '生成方式：`tools/manual_surface.py`；`check.sh` 保证本页与源码一致。', '',
           '公开面共 %d 个成员，其中内部 %d 个：' % (len(rows), sum(1 for r in rows if r[4] == 'internal')), '']
    for mod in sorted(by):
        out.append('## %s' % mod)
        out.append('')
        for ty, name, kind in sorted(by[mod]):
            out.append('- `%s.%s`（%s）' % (ty, name, '字段' if kind == 'field' else '方法'))
        out.append('')
    return '\n'.join(out) + '\n'
page = internals_page()
PAGE = 'docs/manual/20-internals.md'
if '--check' in sys.argv:
    cur = open('tools/manual-surface.txt', encoding='utf-8').read() if os.path.exists('tools/manual-surface.txt') else ''
    curp = open(PAGE, encoding='utf-8').read() if os.path.exists(PAGE) else ''
    if cur != text or curp != page:
        print('工具清单或内部成员页与源码不一致 -- 跑 tools/manual_surface.py'); sys.exit(1)
    print('ok  清单与源码一致（%d 个成员：公开 %d · 内部 %d）' % (
        len(rows), sum(1 for r in rows if r[4] == 'public'), sum(1 for r in rows if r[4] == 'internal'))); sys.exit(0)
open('tools/manual-surface.txt', 'w', encoding='utf-8').write(text)
open(PAGE, 'w', encoding='utf-8').write(page)
bymod = {}
for rel, t, n, k, v in rows:
    if v == 'public': bymod[rel] = bymod.get(rel, 0) + 1
pub = sum(bymod.values())
print('成员共 %d 个：公开 %d · 内部 %d' % (len(rows), pub, len(rows) - pub))
for rel, c in sorted(bymod.items(), key=lambda kv: -kv[1])[:8]: print('  %-16s %3d 公开' % (rel, c))
